from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QKeyEvent
#from PyQt5.QtWidgets import QApplication,QMainWindow, QLabel, QVBoxLayout, QWidget, QPushButton, QHBoxLayout
#from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
import sys, keyboard
from copy import copy
from WORMHOLE import getJSONGUI

class Window(object):
    def __init__(self, MainWindow):
        self.Window = MainWindow
        self.clock_tick = 0

        #Paste UI Generated Code here
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Rout8 = QtWidgets.QWidget(self.centralwidget)
        self.Rout8.setGeometry(QtCore.QRect(410, 0, 301, 331))
        self.Rout8.setObjectName("Rout8")
        self.Buffer_DOWN = QtWidgets.QWidget(self.Rout8)
        self.Buffer_DOWN.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN.setObjectName("Buffer_DOWN")
        self.HighC = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighC.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC.setStyleSheet("background-color: green")
        self.HighC.setObjectName("HighC")
        self.HighB = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighB.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB.setStyleSheet("background-color: green")
        self.HighB.setObjectName("HighB")
        self.HighA = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighA.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA.setStyleSheet("background-color: green")
        self.HighA.setObjectName("HighA")
        self.LowC = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowC.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC.setStyleSheet("background-color: green")
        self.LowC.setObjectName("LowC")
        self.LowB = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowB.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB.setStyleSheet("background-color: green")
        self.LowB.setObjectName("LowB")
        self.LowA = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowA.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA.setStyleSheet("background-color: green")
        self.LowA.setObjectName("LowA")
        self.HighA.raise_()
        self.HighB.raise_()
        self.HighC.raise_()
        self.LowA.raise_()
        self.LowB.raise_()
        self.LowC.raise_()
        self.Buffer_UP = QtWidgets.QWidget(self.Rout8)
        self.Buffer_UP.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP.setObjectName("Buffer_UP")
        self.HighA_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighA_4.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_4.setStyleSheet("background-color: green")
        self.HighA_4.setObjectName("HighA_4")
        self.HighB_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighB_4.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_4.setStyleSheet("background-color: green")
        self.HighB_4.setObjectName("HighB_4")
        self.HighC_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighC_4.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_4.setStyleSheet("background-color: green")
        self.HighC_4.setObjectName("HighC_4")
        self.LowA_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowA_4.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_4.setStyleSheet("background-color: green")
        self.LowA_4.setObjectName("LowA_4")
        self.LowB_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowB_4.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_4.setStyleSheet("background-color: green")
        self.LowB_4.setObjectName("LowB_4")
        self.LowC_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowC_4.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_4.setStyleSheet("background-color: green")
        self.LowC_4.setObjectName("LowC_4")
        self.label = QtWidgets.QLabel(self.Rout8)
        self.label.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label.setObjectName("label")
        self.Buffer_RIGHT = QtWidgets.QWidget(self.Rout8)
        self.Buffer_RIGHT.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT.setObjectName("Buffer_RIGHT")
        self.HighC_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighC_3.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_3.setStyleSheet("background-color: green")
        self.HighC_3.setObjectName("HighC_3")
        self.LowB_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowB_3.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_3.setStyleSheet("background-color: green")
        self.LowB_3.setObjectName("LowB_3")
        self.HighB_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighB_3.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_3.setStyleSheet("background-color: green")
        self.HighB_3.setObjectName("HighB_3")
        self.LowC_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowC_3.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_3.setStyleSheet("background-color: green")
        self.LowC_3.setObjectName("LowC_3")
        self.LowA_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowA_3.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_3.setStyleSheet("background-color: green")
        self.LowA_3.setObjectName("LowA_3")
        self.HighA_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighA_3.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_3.setStyleSheet("background-color: green")
        self.HighA_3.setObjectName("HighA_3")
        self.HighC_3.raise_()
        self.HighB_3.raise_()
        self.HighA_3.raise_()
        self.LowA_3.raise_()
        self.LowB_3.raise_()
        self.LowC_3.raise_()
        self.Buffer_LEFT = QtWidgets.QWidget(self.Rout8)
        self.Buffer_LEFT.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT.setObjectName("Buffer_LEFT")
        self.HighA_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighA_2.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_2.setStyleSheet("background-color: green")
        self.HighA_2.setObjectName("HighA_2")
        self.LowB_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowB_2.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_2.setStyleSheet("background-color: green")
        self.LowB_2.setObjectName("LowB_2")
        self.HighB_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighB_2.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_2.setStyleSheet("background-color: green")
        self.HighB_2.setObjectName("HighB_2")
        self.LowA_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowA_2.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_2.setStyleSheet("background-color: green")
        self.LowA_2.setObjectName("LowA_2")
        self.LowC_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowC_2.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_2.setStyleSheet("background-color: green")
        self.LowC_2.setObjectName("LowC_2")
        self.HighC_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighC_2.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_2.setStyleSheet("background-color: green")
        self.HighC_2.setObjectName("HighC_2")
        self.Buffer_Slave = QtWidgets.QWidget(self.Rout8)
        self.Buffer_Slave.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave.setObjectName("Buffer_Slave")
        self.HighC_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighC_5.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_5.setStyleSheet("background-color: green")
        self.HighC_5.setObjectName("HighC_5")
        self.LowB_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowB_5.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_5.setStyleSheet("background-color: green")
        self.LowB_5.setObjectName("LowB_5")
        self.HighB_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighB_5.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_5.setStyleSheet("background-color: green")
        self.HighB_5.setObjectName("HighB_5")
        self.LowC_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowC_5.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_5.setStyleSheet("background-color: green")
        self.LowC_5.setObjectName("LowC_5")
        self.LowA_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowA_5.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_5.setStyleSheet("background-color: green")
        self.LowA_5.setObjectName("LowA_5")
        self.HighA_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighA_5.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_5.setStyleSheet("background-color: green")
        self.HighA_5.setObjectName("HighA_5")
        self.label.raise_()
        self.Buffer_DOWN.raise_()
        self.Buffer_UP.raise_()
        self.Buffer_RIGHT.raise_()
        self.Buffer_LEFT.raise_()
        self.Buffer_Slave.raise_()
        self.Rout1 = QtWidgets.QWidget(self.centralwidget)
        self.Rout1.setGeometry(QtCore.QRect(800, 0, 291, 331))
        self.Rout1.setObjectName("Rout1")
        self.Buffer_DOWN_2 = QtWidgets.QWidget(self.Rout1)
        self.Buffer_DOWN_2.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_2.setObjectName("Buffer_DOWN_2")
        self.HighC_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.HighC_11.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_11.setStyleSheet("background-color: green")
        self.HighC_11.setObjectName("HighC_11")
        self.HighB_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.HighB_11.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_11.setStyleSheet("background-color: green")
        self.HighB_11.setObjectName("HighB_11")
        self.HighA_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.HighA_11.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_11.setStyleSheet("background-color: green")
        self.HighA_11.setObjectName("HighA_11")
        self.LowC_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.LowC_11.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_11.setStyleSheet("background-color: green")
        self.LowC_11.setObjectName("LowC_11")
        self.LowB_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.LowB_11.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_11.setStyleSheet("background-color: green")
        self.LowB_11.setObjectName("LowB_11")
        self.LowA_11 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.LowA_11.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_11.setStyleSheet("background-color: green")
        self.LowA_11.setObjectName("LowA_11")
        self.Buffer_UP_2 = QtWidgets.QWidget(self.Rout1)
        self.Buffer_UP_2.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_2.setObjectName("Buffer_UP_2")
        self.HighA_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.HighA_14.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_14.setStyleSheet("background-color: green")
        self.HighA_14.setObjectName("HighA_14")
        self.HighB_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.HighB_14.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_14.setStyleSheet("background-color: green")
        self.HighB_14.setObjectName("HighB_14")
        self.HighC_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.HighC_14.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_14.setStyleSheet("background-color: green")
        self.HighC_14.setObjectName("HighC_14")
        self.LowA_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.LowA_14.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_14.setStyleSheet("background-color: green")
        self.LowA_14.setObjectName("LowA_14")
        self.LowB_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.LowB_14.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_14.setStyleSheet("background-color: green")
        self.LowB_14.setObjectName("LowB_14")
        self.LowC_14 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.LowC_14.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_14.setStyleSheet("background-color: green")
        self.LowC_14.setObjectName("LowC_14")
        self.label_2 = QtWidgets.QLabel(self.Rout1)
        self.label_2.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_2.setObjectName("label_2")
        self.Buffer_RIGHT_2 = QtWidgets.QWidget(self.Rout1)
        self.Buffer_RIGHT_2.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_2.setObjectName("Buffer_RIGHT_2")
        self.HighC_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.HighC_13.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_13.setStyleSheet("background-color: green")
        self.HighC_13.setObjectName("HighC_13")
        self.LowB_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.LowB_13.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_13.setStyleSheet("background-color: green")
        self.LowB_13.setObjectName("LowB_13")
        self.HighB_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.HighB_13.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_13.setStyleSheet("background-color: green")
        self.HighB_13.setObjectName("HighB_13")
        self.LowC_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.LowC_13.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_13.setStyleSheet("background-color: green")
        self.LowC_13.setObjectName("LowC_13")
        self.LowA_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.LowA_13.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_13.setStyleSheet("background-color: green")
        self.LowA_13.setObjectName("LowA_13")
        self.HighA_13 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.HighA_13.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_13.setStyleSheet("background-color: green")
        self.HighA_13.setObjectName("HighA_13")
        self.Buffer_LEFT_2 = QtWidgets.QWidget(self.Rout1)
        self.Buffer_LEFT_2.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_2.setObjectName("Buffer_LEFT_2")
        self.HighA_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.HighA_12.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_12.setStyleSheet("background-color: green")
        self.HighA_12.setObjectName("HighA_12")
        self.LowB_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LowB_12.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_12.setStyleSheet("background-color: green")
        self.LowB_12.setObjectName("LowB_12")
        self.HighB_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.HighB_12.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_12.setStyleSheet("background-color: green")
        self.HighB_12.setObjectName("HighB_12")
        self.LowA_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LowA_12.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_12.setStyleSheet("background-color: green")
        self.LowA_12.setObjectName("LowA_12")
        self.LowC_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LowC_12.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_12.setStyleSheet("background-color: green")
        self.LowC_12.setObjectName("LowC_12")
        self.HighC_12 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.HighC_12.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_12.setStyleSheet("background-color: green")
        self.HighC_12.setObjectName("HighC_12")
        self.label_2.raise_()
        self.Buffer_DOWN_2.raise_()
        self.Buffer_UP_2.raise_()
        self.Buffer_RIGHT_2.raise_()
        self.Buffer_LEFT_2.raise_()
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(550, 281, 10, 114))
        self.widget_8.setStyleSheet("background-color: black")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(940, 281, 10, 114))
        self.widget_9.setStyleSheet("background-color: black")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(1332, 281, 10, 114))
        self.widget_10.setStyleSheet("background-color: black")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(1332, 641, 10, 114))
        self.widget_11.setStyleSheet("background-color: black")
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(940, 641, 10, 114))
        self.widget_12.setStyleSheet("background-color: black")
        self.widget_12.setObjectName("widget_12")
        self.widget_33 = QtWidgets.QWidget(self.centralwidget)
        self.widget_33.setGeometry(QtCore.QRect(550, 641, 10, 114))
        self.widget_33.setStyleSheet("background-color: black")
        self.widget_33.setObjectName("widget_33")
        self.widget_34 = QtWidgets.QWidget(self.centralwidget)
        self.widget_34.setGeometry(QtCore.QRect(680, 153, 140, 10))
        self.widget_34.setStyleSheet("background-color: black")
        self.widget_34.setObjectName("widget_34")
        self.widget_47 = QtWidgets.QWidget(self.centralwidget)
        self.widget_47.setGeometry(QtCore.QRect(680, 513, 140, 10))
        self.widget_47.setStyleSheet("background-color: black")
        self.widget_47.setObjectName("widget_47")
        self.widget_48 = QtWidgets.QWidget(self.centralwidget)
        self.widget_48.setGeometry(QtCore.QRect(679, 874, 140, 10))
        self.widget_48.setStyleSheet("background-color: black")
        self.widget_48.setObjectName("widget_48")
        self.widget_49 = QtWidgets.QWidget(self.centralwidget)
        self.widget_49.setGeometry(QtCore.QRect(1069, 874, 144, 10))
        self.widget_49.setStyleSheet("background-color: black")
        self.widget_49.setObjectName("widget_49")
        self.widget_50 = QtWidgets.QWidget(self.centralwidget)
        self.widget_50.setGeometry(QtCore.QRect(1070, 513, 142, 10))
        self.widget_50.setStyleSheet("background-color: black")
        self.widget_50.setObjectName("widget_50")
        self.widget_51 = QtWidgets.QWidget(self.centralwidget)
        self.widget_51.setGeometry(QtCore.QRect(1070, 153, 142, 10))
        self.widget_51.setStyleSheet("background-color: black")
        self.widget_51.setObjectName("widget_51")
        self.Rout7 = QtWidgets.QWidget(self.centralwidget)
        self.Rout7.setGeometry(QtCore.QRect(409, 360, 301, 331))
        self.Rout7.setObjectName("Rout7")
        self.Buffer_DOWN_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_DOWN_3.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_3.setObjectName("Buffer_DOWN_3")
        self.HighC_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighC_6.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_6.setStyleSheet("background-color: green")
        self.HighC_6.setObjectName("HighC_6")
        self.HighB_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighB_6.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_6.setStyleSheet("background-color: green")
        self.HighB_6.setObjectName("HighB_6")
        self.HighA_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighA_6.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_6.setStyleSheet("background-color: green")
        self.HighA_6.setObjectName("HighA_6")
        self.LowC_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowC_6.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_6.setStyleSheet("background-color: green")
        self.LowC_6.setObjectName("LowC_6")
        self.LowB_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowB_6.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_6.setStyleSheet("background-color: green")
        self.LowB_6.setObjectName("LowB_6")
        self.LowA_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowA_6.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_6.setStyleSheet("background-color: green")
        self.LowA_6.setObjectName("LowA_6")
        self.Buffer_UP_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_UP_3.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_3.setObjectName("Buffer_UP_3")
        self.HighA_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighA_7.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_7.setStyleSheet("background-color: green")
        self.HighA_7.setObjectName("HighA_7")
        self.HighB_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighB_7.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_7.setStyleSheet("background-color: green")
        self.HighB_7.setObjectName("HighB_7")
        self.HighC_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighC_7.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_7.setStyleSheet("background-color: green")
        self.HighC_7.setObjectName("HighC_7")
        self.LowA_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowA_7.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_7.setStyleSheet("background-color: green")
        self.LowA_7.setObjectName("LowA_7")
        self.LowB_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowB_7.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_7.setStyleSheet("background-color: green")
        self.LowB_7.setObjectName("LowB_7")
        self.LowC_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowC_7.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_7.setStyleSheet("background-color: green")
        self.LowC_7.setObjectName("LowC_7")
        self.label_3 = QtWidgets.QLabel(self.Rout7)
        self.label_3.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_3.setObjectName("label_3")
        self.Buffer_RIGHT_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_RIGHT_3.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_3.setObjectName("Buffer_RIGHT_3")
        self.HighC_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighC_8.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_8.setStyleSheet("background-color: green")
        self.HighC_8.setObjectName("HighC_8")
        self.LowB_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowB_8.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_8.setStyleSheet("background-color: green")
        self.LowB_8.setObjectName("LowB_8")
        self.HighB_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighB_8.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_8.setStyleSheet("background-color: green")
        self.HighB_8.setObjectName("HighB_8")
        self.LowC_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowC_8.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_8.setStyleSheet("background-color: green")
        self.LowC_8.setObjectName("LowC_8")
        self.LowA_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowA_8.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_8.setStyleSheet("background-color: green")
        self.LowA_8.setObjectName("LowA_8")
        self.HighA_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighA_8.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_8.setStyleSheet("background-color: green")
        self.HighA_8.setObjectName("HighA_8")
        self.Buffer_LEFT_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_LEFT_3.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_3.setObjectName("Buffer_LEFT_3")
        self.HighA_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighA_9.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_9.setStyleSheet("background-color: green")
        self.HighA_9.setObjectName("HighA_9")
        self.LowB_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowB_9.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_9.setStyleSheet("background-color: green")
        self.LowB_9.setObjectName("LowB_9")
        self.HighB_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighB_9.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_9.setStyleSheet("background-color: green")
        self.HighB_9.setObjectName("HighB_9")
        self.LowA_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowA_9.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_9.setStyleSheet("background-color: green")
        self.LowA_9.setObjectName("LowA_9")
        self.LowC_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowC_9.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_9.setStyleSheet("background-color: green")
        self.LowC_9.setObjectName("LowC_9")
        self.HighC_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighC_9.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_9.setStyleSheet("background-color: green")
        self.HighC_9.setObjectName("HighC_9")
        self.Buffer_Slave_2 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_Slave_2.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_2.setObjectName("Buffer_Slave_2")
        self.HighC_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighC_10.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_10.setStyleSheet("background-color: green")
        self.HighC_10.setObjectName("HighC_10")
        self.LowB_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowB_10.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_10.setStyleSheet("background-color: green")
        self.LowB_10.setObjectName("LowB_10")
        self.HighB_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighB_10.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_10.setStyleSheet("background-color: green")
        self.HighB_10.setObjectName("HighB_10")
        self.LowC_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowC_10.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_10.setStyleSheet("background-color: green")
        self.LowC_10.setObjectName("LowC_10")
        self.LowA_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowA_10.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_10.setStyleSheet("background-color: green")
        self.LowA_10.setObjectName("LowA_10")
        self.HighA_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighA_10.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_10.setStyleSheet("background-color: green")
        self.HighA_10.setObjectName("HighA_10")
        self.label_3.raise_()
        self.Buffer_RIGHT_3.raise_()
        self.Buffer_LEFT_3.raise_()
        self.Buffer_Slave_2.raise_()
        self.Buffer_DOWN_3.raise_()
        self.Buffer_UP_3.raise_()
        self.Rout0 = QtWidgets.QWidget(self.centralwidget)
        self.Rout0.setGeometry(QtCore.QRect(800, 360, 291, 331))
        self.Rout0.setObjectName("Rout0")
        self.Buffer_DOWN_4 = QtWidgets.QWidget(self.Rout0)
        self.Buffer_DOWN_4.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_4.setObjectName("Buffer_DOWN_4")
        self.HighC_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.HighC_15.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_15.setStyleSheet("background-color: green")
        self.HighC_15.setObjectName("HighC_15")
        self.HighB_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.HighB_15.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_15.setStyleSheet("background-color: green")
        self.HighB_15.setObjectName("HighB_15")
        self.HighA_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.HighA_15.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_15.setStyleSheet("background-color: green")
        self.HighA_15.setObjectName("HighA_15")
        self.LowC_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.LowC_15.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_15.setStyleSheet("background-color: green")
        self.LowC_15.setObjectName("LowC_15")
        self.LowB_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.LowB_15.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_15.setStyleSheet("background-color: green")
        self.LowB_15.setObjectName("LowB_15")
        self.LowA_15 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.LowA_15.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_15.setStyleSheet("background-color: green")
        self.LowA_15.setObjectName("LowA_15")
        self.Buffer_UP_4 = QtWidgets.QWidget(self.Rout0)
        self.Buffer_UP_4.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_4.setObjectName("Buffer_UP_4")
        self.HighA_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.HighA_16.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_16.setStyleSheet("background-color: green")
        self.HighA_16.setObjectName("HighA_16")
        self.HighB_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.HighB_16.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_16.setStyleSheet("background-color: green")
        self.HighB_16.setObjectName("HighB_16")
        self.HighC_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.HighC_16.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_16.setStyleSheet("background-color: green")
        self.HighC_16.setObjectName("HighC_16")
        self.LowA_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.LowA_16.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_16.setStyleSheet("background-color: green")
        self.LowA_16.setObjectName("LowA_16")
        self.LowB_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.LowB_16.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_16.setStyleSheet("background-color: green")
        self.LowB_16.setObjectName("LowB_16")
        self.LowC_16 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.LowC_16.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_16.setStyleSheet("background-color: green")
        self.LowC_16.setObjectName("LowC_16")
        self.label_4 = QtWidgets.QLabel(self.Rout0)
        self.label_4.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_4.setObjectName("label_4")
        self.Buffer_RIGHT_4 = QtWidgets.QWidget(self.Rout0)
        self.Buffer_RIGHT_4.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_4.setObjectName("Buffer_RIGHT_4")
        self.HighC_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.HighC_17.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_17.setStyleSheet("background-color: green")
        self.HighC_17.setObjectName("HighC_17")
        self.LowB_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.LowB_17.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_17.setStyleSheet("background-color: green")
        self.LowB_17.setObjectName("LowB_17")
        self.HighB_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.HighB_17.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_17.setStyleSheet("background-color: green")
        self.HighB_17.setObjectName("HighB_17")
        self.LowC_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.LowC_17.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_17.setStyleSheet("background-color: green")
        self.LowC_17.setObjectName("LowC_17")
        self.LowA_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.LowA_17.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_17.setStyleSheet("background-color: green")
        self.LowA_17.setObjectName("LowA_17")
        self.HighA_17 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.HighA_17.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_17.setStyleSheet("background-color: green")
        self.HighA_17.setObjectName("HighA_17")
        self.Buffer_LEFT_4 = QtWidgets.QWidget(self.Rout0)
        self.Buffer_LEFT_4.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_4.setObjectName("Buffer_LEFT_4")
        self.HighA_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.HighA_18.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_18.setStyleSheet("background-color: green")
        self.HighA_18.setObjectName("HighA_18")
        self.LowB_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LowB_18.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_18.setStyleSheet("background-color: green")
        self.LowB_18.setObjectName("LowB_18")
        self.HighB_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.HighB_18.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_18.setStyleSheet("background-color: green")
        self.HighB_18.setObjectName("HighB_18")
        self.LowA_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LowA_18.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_18.setStyleSheet("background-color: green")
        self.LowA_18.setObjectName("LowA_18")
        self.LowC_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LowC_18.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_18.setStyleSheet("background-color: green")
        self.LowC_18.setObjectName("LowC_18")
        self.HighC_18 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.HighC_18.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_18.setStyleSheet("background-color: green")
        self.HighC_18.setObjectName("HighC_18")
        self.label_4.raise_()
        self.Buffer_RIGHT_4.raise_()
        self.Buffer_LEFT_4.raise_()
        self.Buffer_DOWN_4.raise_()
        self.Buffer_UP_4.raise_()
        self.Rout6 = QtWidgets.QWidget(self.centralwidget)
        self.Rout6.setGeometry(QtCore.QRect(409, 720, 291, 331))
        self.Rout6.setObjectName("Rout6")
        self.Buffer_DOWN_5 = QtWidgets.QWidget(self.Rout6)
        self.Buffer_DOWN_5.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_5.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_5.setObjectName("Buffer_DOWN_5")
        self.HighC_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.HighC_19.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_19.setStyleSheet("background-color: green")
        self.HighC_19.setObjectName("HighC_19")
        self.HighB_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.HighB_19.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_19.setStyleSheet("background-color: green")
        self.HighB_19.setObjectName("HighB_19")
        self.HighA_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.HighA_19.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_19.setStyleSheet("background-color: green")
        self.HighA_19.setObjectName("HighA_19")
        self.LowC_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.LowC_19.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_19.setStyleSheet("background-color: green")
        self.LowC_19.setObjectName("LowC_19")
        self.LowB_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.LowB_19.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_19.setStyleSheet("background-color: green")
        self.LowB_19.setObjectName("LowB_19")
        self.LowA_19 = QtWidgets.QWidget(self.Buffer_DOWN_5)
        self.LowA_19.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_19.setStyleSheet("background-color: green")
        self.LowA_19.setObjectName("LowA_19")
        self.Buffer_UP_5 = QtWidgets.QWidget(self.Rout6)
        self.Buffer_UP_5.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_5.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_5.setObjectName("Buffer_UP_5")
        self.HighA_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.HighA_20.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_20.setStyleSheet("background-color: green")
        self.HighA_20.setObjectName("HighA_20")
        self.HighB_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.HighB_20.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_20.setStyleSheet("background-color: green")
        self.HighB_20.setObjectName("HighB_20")
        self.HighC_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.HighC_20.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_20.setStyleSheet("background-color: green")
        self.HighC_20.setObjectName("HighC_20")
        self.LowA_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.LowA_20.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_20.setStyleSheet("background-color: green")
        self.LowA_20.setObjectName("LowA_20")
        self.LowB_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.LowB_20.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_20.setStyleSheet("background-color: green")
        self.LowB_20.setObjectName("LowB_20")
        self.LowC_20 = QtWidgets.QWidget(self.Buffer_UP_5)
        self.LowC_20.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_20.setStyleSheet("background-color: green")
        self.LowC_20.setObjectName("LowC_20")
        self.label_5 = QtWidgets.QLabel(self.Rout6)
        self.label_5.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_5.setObjectName("label_5")
        self.Buffer_RIGHT_5 = QtWidgets.QWidget(self.Rout6)
        self.Buffer_RIGHT_5.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_5.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_5.setObjectName("Buffer_RIGHT_5")
        self.HighC_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.HighC_21.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_21.setStyleSheet("background-color: green")
        self.HighC_21.setObjectName("HighC_21")
        self.LowB_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.LowB_21.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_21.setStyleSheet("background-color: green")
        self.LowB_21.setObjectName("LowB_21")
        self.HighB_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.HighB_21.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_21.setStyleSheet("background-color: green")
        self.HighB_21.setObjectName("HighB_21")
        self.LowC_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.LowC_21.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_21.setStyleSheet("background-color: green")
        self.LowC_21.setObjectName("LowC_21")
        self.LowA_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.LowA_21.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_21.setStyleSheet("background-color: green")
        self.LowA_21.setObjectName("LowA_21")
        self.HighA_21 = QtWidgets.QWidget(self.Buffer_RIGHT_5)
        self.HighA_21.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_21.setStyleSheet("background-color: green")
        self.HighA_21.setObjectName("HighA_21")
        self.Buffer_LEFT_5 = QtWidgets.QWidget(self.Rout6)
        self.Buffer_LEFT_5.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_5.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_5.setObjectName("Buffer_LEFT_5")
        self.HighA_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.HighA_22.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_22.setStyleSheet("background-color: green")
        self.HighA_22.setObjectName("HighA_22")
        self.LowB_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.LowB_22.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_22.setStyleSheet("background-color: green")
        self.LowB_22.setObjectName("LowB_22")
        self.HighB_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.HighB_22.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_22.setStyleSheet("background-color: green")
        self.HighB_22.setObjectName("HighB_22")
        self.LowA_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.LowA_22.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_22.setStyleSheet("background-color: green")
        self.LowA_22.setObjectName("LowA_22")
        self.LowC_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.LowC_22.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_22.setStyleSheet("background-color: green")
        self.LowC_22.setObjectName("LowC_22")
        self.HighC_22 = QtWidgets.QWidget(self.Buffer_LEFT_5)
        self.HighC_22.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_22.setStyleSheet("background-color: green")
        self.HighC_22.setObjectName("HighC_22")
        self.label_5.raise_()
        self.Buffer_RIGHT_5.raise_()
        self.Buffer_LEFT_5.raise_()
        self.Buffer_DOWN_5.raise_()
        self.Buffer_UP_5.raise_()
        self.Rout4 = QtWidgets.QWidget(self.centralwidget)
        self.Rout4.setGeometry(QtCore.QRect(1192, 720, 291, 331))
        self.Rout4.setObjectName("Rout4")
        self.Buffer_DOWN_7 = QtWidgets.QWidget(self.Rout4)
        self.Buffer_DOWN_7.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_7.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_7.setObjectName("Buffer_DOWN_7")
        self.HighC_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.HighC_23.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_23.setStyleSheet("background-color: green")
        self.HighC_23.setObjectName("HighC_23")
        self.HighB_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.HighB_23.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_23.setStyleSheet("background-color: green")
        self.HighB_23.setObjectName("HighB_23")
        self.HighA_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.HighA_23.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_23.setStyleSheet("background-color: green")
        self.HighA_23.setObjectName("HighA_23")
        self.LowC_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.LowC_23.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_23.setStyleSheet("background-color: green")
        self.LowC_23.setObjectName("LowC_23")
        self.LowB_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.LowB_23.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_23.setStyleSheet("background-color: green")
        self.LowB_23.setObjectName("LowB_23")
        self.LowA_23 = QtWidgets.QWidget(self.Buffer_DOWN_7)
        self.LowA_23.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_23.setStyleSheet("background-color: green")
        self.LowA_23.setObjectName("LowA_23")
        self.Buffer_UP_7 = QtWidgets.QWidget(self.Rout4)
        self.Buffer_UP_7.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_7.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_7.setObjectName("Buffer_UP_7")
        self.HighA_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.HighA_24.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_24.setStyleSheet("background-color: green")
        self.HighA_24.setObjectName("HighA_24")
        self.HighB_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.HighB_24.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_24.setStyleSheet("background-color: green")
        self.HighB_24.setObjectName("HighB_24")
        self.HighC_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.HighC_24.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_24.setStyleSheet("background-color: green")
        self.HighC_24.setObjectName("HighC_24")
        self.LowA_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.LowA_24.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_24.setStyleSheet("background-color: green")
        self.LowA_24.setObjectName("LowA_24")
        self.LowB_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.LowB_24.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_24.setStyleSheet("background-color: green")
        self.LowB_24.setObjectName("LowB_24")
        self.LowC_24 = QtWidgets.QWidget(self.Buffer_UP_7)
        self.LowC_24.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_24.setStyleSheet("background-color: green")
        self.LowC_24.setObjectName("LowC_24")
        self.label_7 = QtWidgets.QLabel(self.Rout4)
        self.label_7.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_7.setObjectName("label_7")
        self.Buffer_RIGHT_7 = QtWidgets.QWidget(self.Rout4)
        self.Buffer_RIGHT_7.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_7.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_7.setObjectName("Buffer_RIGHT_7")
        self.HighC_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.HighC_25.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_25.setStyleSheet("background-color: green")
        self.HighC_25.setObjectName("HighC_25")
        self.LowB_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.LowB_25.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_25.setStyleSheet("background-color: green")
        self.LowB_25.setObjectName("LowB_25")
        self.HighB_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.HighB_25.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_25.setStyleSheet("background-color: green")
        self.HighB_25.setObjectName("HighB_25")
        self.LowC_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.LowC_25.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_25.setStyleSheet("background-color: green")
        self.LowC_25.setObjectName("LowC_25")
        self.LowA_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.LowA_25.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_25.setStyleSheet("background-color: green")
        self.LowA_25.setObjectName("LowA_25")
        self.HighA_25 = QtWidgets.QWidget(self.Buffer_RIGHT_7)
        self.HighA_25.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_25.setStyleSheet("background-color: green")
        self.HighA_25.setObjectName("HighA_25")
        self.Buffer_LEFT_7 = QtWidgets.QWidget(self.Rout4)
        self.Buffer_LEFT_7.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_7.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_7.setObjectName("Buffer_LEFT_7")
        self.HighA_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.HighA_26.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_26.setStyleSheet("background-color: green")
        self.HighA_26.setObjectName("HighA_26")
        self.LowB_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.LowB_26.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_26.setStyleSheet("background-color: green")
        self.LowB_26.setObjectName("LowB_26")
        self.HighB_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.HighB_26.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_26.setStyleSheet("background-color: green")
        self.HighB_26.setObjectName("HighB_26")
        self.LowA_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.LowA_26.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_26.setStyleSheet("background-color: green")
        self.LowA_26.setObjectName("LowA_26")
        self.LowC_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.LowC_26.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_26.setStyleSheet("background-color: green")
        self.LowC_26.setObjectName("LowC_26")
        self.HighC_26 = QtWidgets.QWidget(self.Buffer_LEFT_7)
        self.HighC_26.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_26.setStyleSheet("background-color: green")
        self.HighC_26.setObjectName("HighC_26")
        self.label_7.raise_()
        self.Buffer_DOWN_7.raise_()
        self.Buffer_UP_7.raise_()
        self.Buffer_RIGHT_7.raise_()
        self.Buffer_LEFT_7.raise_()
        self.Rout2 = QtWidgets.QWidget(self.centralwidget)
        self.Rout2.setGeometry(QtCore.QRect(1192, 0, 301, 331))
        self.Rout2.setObjectName("Rout2")
        self.Buffer_DOWN_6 = QtWidgets.QWidget(self.Rout2)
        self.Buffer_DOWN_6.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_6.setObjectName("Buffer_DOWN_6")
        self.HighC_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.HighC_27.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_27.setStyleSheet("background-color: green")
        self.HighC_27.setObjectName("HighC_27")
        self.HighB_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.HighB_27.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_27.setStyleSheet("background-color: green")
        self.HighB_27.setObjectName("HighB_27")
        self.HighA_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.HighA_27.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_27.setStyleSheet("background-color: green")
        self.HighA_27.setObjectName("HighA_27")
        self.LowC_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.LowC_27.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_27.setStyleSheet("background-color: green")
        self.LowC_27.setObjectName("LowC_27")
        self.LowB_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.LowB_27.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_27.setStyleSheet("background-color: green")
        self.LowB_27.setObjectName("LowB_27")
        self.LowA_27 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.LowA_27.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_27.setStyleSheet("background-color: green")
        self.LowA_27.setObjectName("LowA_27")
        self.Buffer_UP_6 = QtWidgets.QWidget(self.Rout2)
        self.Buffer_UP_6.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_6.setObjectName("Buffer_UP_6")
        self.HighA_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.HighA_28.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_28.setStyleSheet("background-color: green")
        self.HighA_28.setObjectName("HighA_28")
        self.HighB_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.HighB_28.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_28.setStyleSheet("background-color: green")
        self.HighB_28.setObjectName("HighB_28")
        self.HighC_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.HighC_28.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_28.setStyleSheet("background-color: green")
        self.HighC_28.setObjectName("HighC_28")
        self.LowA_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.LowA_28.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_28.setStyleSheet("background-color: green")
        self.LowA_28.setObjectName("LowA_28")
        self.LowB_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.LowB_28.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_28.setStyleSheet("background-color: green")
        self.LowB_28.setObjectName("LowB_28")
        self.LowC_28 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.LowC_28.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_28.setStyleSheet("background-color: green")
        self.LowC_28.setObjectName("LowC_28")
        self.label_6 = QtWidgets.QLabel(self.Rout2)
        self.label_6.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_6.setObjectName("label_6")
        self.Buffer_RIGHT_6 = QtWidgets.QWidget(self.Rout2)
        self.Buffer_RIGHT_6.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_6.setObjectName("Buffer_RIGHT_6")
        self.HighC_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.HighC_29.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_29.setStyleSheet("background-color: green")
        self.HighC_29.setObjectName("HighC_29")
        self.LowB_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.LowB_29.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_29.setStyleSheet("background-color: green")
        self.LowB_29.setObjectName("LowB_29")
        self.HighB_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.HighB_29.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_29.setStyleSheet("background-color: green")
        self.HighB_29.setObjectName("HighB_29")
        self.LowC_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.LowC_29.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_29.setStyleSheet("background-color: green")
        self.LowC_29.setObjectName("LowC_29")
        self.LowA_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.LowA_29.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_29.setStyleSheet("background-color: green")
        self.LowA_29.setObjectName("LowA_29")
        self.HighA_29 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.HighA_29.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_29.setStyleSheet("background-color: green")
        self.HighA_29.setObjectName("HighA_29")
        self.Buffer_LEFT_6 = QtWidgets.QWidget(self.Rout2)
        self.Buffer_LEFT_6.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_6.setObjectName("Buffer_LEFT_6")
        self.HighA_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.HighA_30.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_30.setStyleSheet("background-color: green")
        self.HighA_30.setObjectName("HighA_30")
        self.LowB_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LowB_30.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_30.setStyleSheet("background-color: green")
        self.LowB_30.setObjectName("LowB_30")
        self.HighB_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.HighB_30.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_30.setStyleSheet("background-color: green")
        self.HighB_30.setObjectName("HighB_30")
        self.LowA_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LowA_30.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_30.setStyleSheet("background-color: green")
        self.LowA_30.setObjectName("LowA_30")
        self.LowC_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LowC_30.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_30.setStyleSheet("background-color: green")
        self.LowC_30.setObjectName("LowC_30")
        self.HighC_30 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.HighC_30.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_30.setStyleSheet("background-color: green")
        self.HighC_30.setObjectName("HighC_30")
        self.Buffer_Slave_3 = QtWidgets.QWidget(self.Rout2)
        self.Buffer_Slave_3.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_3.setObjectName("Buffer_Slave_3")
        self.HighC_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.HighC_31.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_31.setStyleSheet("background-color: green")
        self.HighC_31.setObjectName("HighC_31")
        self.LowB_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.LowB_31.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_31.setStyleSheet("background-color: green")
        self.LowB_31.setObjectName("LowB_31")
        self.HighB_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.HighB_31.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_31.setStyleSheet("background-color: green")
        self.HighB_31.setObjectName("HighB_31")
        self.LowC_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.LowC_31.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_31.setStyleSheet("background-color: green")
        self.LowC_31.setObjectName("LowC_31")
        self.LowA_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.LowA_31.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_31.setStyleSheet("background-color: green")
        self.LowA_31.setObjectName("LowA_31")
        self.HighA_31 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.HighA_31.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_31.setStyleSheet("background-color: green")
        self.HighA_31.setObjectName("HighA_31")
        self.label_6.raise_()
        self.Buffer_DOWN_6.raise_()
        self.Buffer_UP_6.raise_()
        self.Buffer_RIGHT_6.raise_()
        self.Buffer_LEFT_6.raise_()
        self.Buffer_Slave_3.raise_()
        self.Rout3 = QtWidgets.QWidget(self.centralwidget)
        self.Rout3.setGeometry(QtCore.QRect(1191, 360, 301, 331))
        self.Rout3.setObjectName("Rout3")
        self.Buffer_DOWN_8 = QtWidgets.QWidget(self.Rout3)
        self.Buffer_DOWN_8.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_8.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_8.setObjectName("Buffer_DOWN_8")
        self.HighC_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.HighC_32.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_32.setStyleSheet("background-color: green")
        self.HighC_32.setObjectName("HighC_32")
        self.HighB_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.HighB_32.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_32.setStyleSheet("background-color: green")
        self.HighB_32.setObjectName("HighB_32")
        self.HighA_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.HighA_32.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_32.setStyleSheet("background-color: green")
        self.HighA_32.setObjectName("HighA_32")
        self.LowC_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.LowC_32.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_32.setStyleSheet("background-color: green")
        self.LowC_32.setObjectName("LowC_32")
        self.LowB_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.LowB_32.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_32.setStyleSheet("background-color: green")
        self.LowB_32.setObjectName("LowB_32")
        self.LowA_32 = QtWidgets.QWidget(self.Buffer_DOWN_8)
        self.LowA_32.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_32.setStyleSheet("background-color: green")
        self.LowA_32.setObjectName("LowA_32")
        self.Buffer_UP_8 = QtWidgets.QWidget(self.Rout3)
        self.Buffer_UP_8.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_8.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_8.setObjectName("Buffer_UP_8")
        self.HighA_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.HighA_33.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_33.setStyleSheet("background-color: green")
        self.HighA_33.setObjectName("HighA_33")
        self.HighB_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.HighB_33.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_33.setStyleSheet("background-color: green")
        self.HighB_33.setObjectName("HighB_33")
        self.HighC_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.HighC_33.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_33.setStyleSheet("background-color: green")
        self.HighC_33.setObjectName("HighC_33")
        self.LowA_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.LowA_33.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_33.setStyleSheet("background-color: green")
        self.LowA_33.setObjectName("LowA_33")
        self.LowB_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.LowB_33.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_33.setStyleSheet("background-color: green")
        self.LowB_33.setObjectName("LowB_33")
        self.LowC_33 = QtWidgets.QWidget(self.Buffer_UP_8)
        self.LowC_33.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_33.setStyleSheet("background-color: green")
        self.LowC_33.setObjectName("LowC_33")
        self.label_8 = QtWidgets.QLabel(self.Rout3)
        self.label_8.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_8.setObjectName("label_8")
        self.Buffer_RIGHT_8 = QtWidgets.QWidget(self.Rout3)
        self.Buffer_RIGHT_8.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_8.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_8.setObjectName("Buffer_RIGHT_8")
        self.HighC_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.HighC_34.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_34.setStyleSheet("background-color: green")
        self.HighC_34.setObjectName("HighC_34")
        self.LowB_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.LowB_34.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_34.setStyleSheet("background-color: green")
        self.LowB_34.setObjectName("LowB_34")
        self.HighB_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.HighB_34.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_34.setStyleSheet("background-color: green")
        self.HighB_34.setObjectName("HighB_34")
        self.LowC_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.LowC_34.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_34.setStyleSheet("background-color: green")
        self.LowC_34.setObjectName("LowC_34")
        self.LowA_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.LowA_34.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_34.setStyleSheet("background-color: green")
        self.LowA_34.setObjectName("LowA_34")
        self.HighA_34 = QtWidgets.QWidget(self.Buffer_RIGHT_8)
        self.HighA_34.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_34.setStyleSheet("background-color: green")
        self.HighA_34.setObjectName("HighA_34")
        self.Buffer_LEFT_8 = QtWidgets.QWidget(self.Rout3)
        self.Buffer_LEFT_8.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_8.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_8.setObjectName("Buffer_LEFT_8")
        self.HighA_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.HighA_35.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_35.setStyleSheet("background-color: green")
        self.HighA_35.setObjectName("HighA_35")
        self.LowB_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.LowB_35.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_35.setStyleSheet("background-color: green")
        self.LowB_35.setObjectName("LowB_35")
        self.HighB_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.HighB_35.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_35.setStyleSheet("background-color: green")
        self.HighB_35.setObjectName("HighB_35")
        self.LowA_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.LowA_35.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_35.setStyleSheet("background-color: green")
        self.LowA_35.setObjectName("LowA_35")
        self.LowC_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.LowC_35.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_35.setStyleSheet("background-color: green")
        self.LowC_35.setObjectName("LowC_35")
        self.HighC_35 = QtWidgets.QWidget(self.Buffer_LEFT_8)
        self.HighC_35.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_35.setStyleSheet("background-color: green")
        self.HighC_35.setObjectName("HighC_35")
        self.Buffer_Slave_4 = QtWidgets.QWidget(self.Rout3)
        self.Buffer_Slave_4.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_4.setObjectName("Buffer_Slave_4")
        self.HighC_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.HighC_36.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_36.setStyleSheet("background-color: green")
        self.HighC_36.setObjectName("HighC_36")
        self.LowB_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.LowB_36.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_36.setStyleSheet("background-color: green")
        self.LowB_36.setObjectName("LowB_36")
        self.HighB_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.HighB_36.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_36.setStyleSheet("background-color: green")
        self.HighB_36.setObjectName("HighB_36")
        self.LowC_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.LowC_36.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_36.setStyleSheet("background-color: green")
        self.LowC_36.setObjectName("LowC_36")
        self.LowA_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.LowA_36.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_36.setStyleSheet("background-color: green")
        self.LowA_36.setObjectName("LowA_36")
        self.HighA_36 = QtWidgets.QWidget(self.Buffer_Slave_4)
        self.HighA_36.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_36.setStyleSheet("background-color: green")
        self.HighA_36.setObjectName("HighA_36")
        self.label_8.raise_()
        self.Buffer_RIGHT_8.raise_()
        self.Buffer_LEFT_8.raise_()
        self.Buffer_Slave_4.raise_()
        self.Buffer_DOWN_8.raise_()
        self.Buffer_UP_8.raise_()
        self.Rout5 = QtWidgets.QWidget(self.centralwidget)
        self.Rout5.setGeometry(QtCore.QRect(799, 720, 301, 331))
        self.Rout5.setObjectName("Rout5")
        self.Buffer_DOWN_9 = QtWidgets.QWidget(self.Rout5)
        self.Buffer_DOWN_9.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_9.setObjectName("Buffer_DOWN_9")
        self.HighC_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.HighC_37.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_37.setStyleSheet("background-color: green")
        self.HighC_37.setObjectName("HighC_37")
        self.HighB_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.HighB_37.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_37.setStyleSheet("background-color: green")
        self.HighB_37.setObjectName("HighB_37")
        self.HighA_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.HighA_37.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_37.setStyleSheet("background-color: green")
        self.HighA_37.setObjectName("HighA_37")
        self.LowC_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.LowC_37.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_37.setStyleSheet("background-color: green")
        self.LowC_37.setObjectName("LowC_37")
        self.LowB_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.LowB_37.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_37.setStyleSheet("background-color: green")
        self.LowB_37.setObjectName("LowB_37")
        self.LowA_37 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.LowA_37.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_37.setStyleSheet("background-color: green")
        self.LowA_37.setObjectName("LowA_37")
        self.Buffer_UP_9 = QtWidgets.QWidget(self.Rout5)
        self.Buffer_UP_9.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_9.setObjectName("Buffer_UP_9")
        self.HighA_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.HighA_38.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_38.setStyleSheet("background-color: green")
        self.HighA_38.setObjectName("HighA_38")
        self.HighB_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.HighB_38.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_38.setStyleSheet("background-color: green")
        self.HighB_38.setObjectName("HighB_38")
        self.HighC_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.HighC_38.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_38.setStyleSheet("background-color: green")
        self.HighC_38.setObjectName("HighC_38")
        self.LowA_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.LowA_38.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_38.setStyleSheet("background-color: green")
        self.LowA_38.setObjectName("LowA_38")
        self.LowB_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.LowB_38.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_38.setStyleSheet("background-color: green")
        self.LowB_38.setObjectName("LowB_38")
        self.LowC_38 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.LowC_38.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_38.setStyleSheet("background-color: green")
        self.LowC_38.setObjectName("LowC_38")
        self.label_9 = QtWidgets.QLabel(self.Rout5)
        self.label_9.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_9.setObjectName("label_9")
        self.Buffer_RIGHT_9 = QtWidgets.QWidget(self.Rout5)
        self.Buffer_RIGHT_9.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_9.setObjectName("Buffer_RIGHT_9")
        self.HighC_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.HighC_39.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_39.setStyleSheet("background-color: green")
        self.HighC_39.setObjectName("HighC_39")
        self.LowB_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.LowB_39.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_39.setStyleSheet("background-color: green")
        self.LowB_39.setObjectName("LowB_39")
        self.HighB_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.HighB_39.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_39.setStyleSheet("background-color: green")
        self.HighB_39.setObjectName("HighB_39")
        self.LowC_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.LowC_39.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_39.setStyleSheet("background-color: green")
        self.LowC_39.setObjectName("LowC_39")
        self.LowA_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.LowA_39.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_39.setStyleSheet("background-color: green")
        self.LowA_39.setObjectName("LowA_39")
        self.HighA_39 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.HighA_39.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_39.setStyleSheet("background-color: green")
        self.HighA_39.setObjectName("HighA_39")
        self.Buffer_LEFT_9 = QtWidgets.QWidget(self.Rout5)
        self.Buffer_LEFT_9.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_9.setObjectName("Buffer_LEFT_9")
        self.HighA_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.HighA_40.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_40.setStyleSheet("background-color: green")
        self.HighA_40.setObjectName("HighA_40")
        self.LowB_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LowB_40.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_40.setStyleSheet("background-color: green")
        self.LowB_40.setObjectName("LowB_40")
        self.HighB_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.HighB_40.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_40.setStyleSheet("background-color: green")
        self.HighB_40.setObjectName("HighB_40")
        self.LowA_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LowA_40.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_40.setStyleSheet("background-color: green")
        self.LowA_40.setObjectName("LowA_40")
        self.LowC_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LowC_40.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_40.setStyleSheet("background-color: green")
        self.LowC_40.setObjectName("LowC_40")
        self.HighC_40 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.HighC_40.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_40.setStyleSheet("background-color: green")
        self.HighC_40.setObjectName("HighC_40")
        self.Buffer_Slave_5 = QtWidgets.QWidget(self.Rout5)
        self.Buffer_Slave_5.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_5.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_5.setObjectName("Buffer_Slave_5")
        self.HighC_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.HighC_41.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_41.setStyleSheet("background-color: green")
        self.HighC_41.setObjectName("HighC_41")
        self.LowB_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.LowB_41.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_41.setStyleSheet("background-color: green")
        self.LowB_41.setObjectName("LowB_41")
        self.HighB_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.HighB_41.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_41.setStyleSheet("background-color: green")
        self.HighB_41.setObjectName("HighB_41")
        self.LowC_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.LowC_41.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_41.setStyleSheet("background-color: green")
        self.LowC_41.setObjectName("LowC_41")
        self.LowA_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.LowA_41.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_41.setStyleSheet("background-color: green")
        self.LowA_41.setObjectName("LowA_41")
        self.HighA_41 = QtWidgets.QWidget(self.Buffer_Slave_5)
        self.HighA_41.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_41.setStyleSheet("background-color: green")
        self.HighA_41.setObjectName("HighA_41")
        self.label_9.raise_()
        self.Buffer_RIGHT_9.raise_()
        self.Buffer_LEFT_9.raise_()
        self.Buffer_Slave_5.raise_()
        self.Buffer_DOWN_9.raise_()
        self.Buffer_UP_9.raise_()
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 401, 111))
        self.widget.setObjectName("widget")
        self.Timer = QtWidgets.QLabel(self.widget)
        self.Timer.setGeometry(QtCore.QRect(0, 0, 401, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.Timer.setFont(font)
        self.Timer.setObjectName("Timer")
        self.Rout2.raise_()
        self.Rout3.raise_()
        self.Rout5.raise_()
        self.Rout4.raise_()
        self.Rout6.raise_()
        self.Rout8.raise_()
        self.Rout1.raise_()
        self.widget_10.raise_()
        self.widget_11.raise_()
        self.widget_34.raise_()
        self.widget_48.raise_()
        self.widget_49.raise_()
        self.widget_51.raise_()
        self.Rout7.raise_()
        self.widget_8.raise_()
        self.widget_33.raise_()
        self.Rout0.raise_()
        self.widget_47.raise_()
        self.widget_50.raise_()
        self.widget_9.raise_()
        self.widget_12.raise_()
        self.widget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionToggle_Fullscreen = QtWidgets.QAction(MainWindow)
        self.actionToggle_Fullscreen.setObjectName("actionToggle_Fullscreen")
        self.menuSettings.addAction(self.actionToggle_Fullscreen)
        self.menubar.addAction(self.menuSettings.menuAction())


        self.centralwidget.setFocusPolicy(Qt.StrongFocus)
        self.Window.keyPressEvent = self.keyPressEvent
    
    def Get_Sorted_Buffer_points(self, Buffer):
        children = Buffer.children()
        sorted_children = sorted(children, key=lambda child: child.objectName())
        return sorted_children

    def Get_Colors(self, Low_Priority_Buffer, High_Priority_Buffer):
        colors = copy(Low_Priority_Buffer)
        while(len(colors) < 3):
            colors.append("white")
        for x in copy(High_Priority_Buffer):
            colors.append(x)
        while(len(colors) < 6):
            colors.append("white")
        return colors
    
    def Color_Buffers(self, Buffer, colors):
        counter = 0
        buffer_points = self.Get_Sorted_Buffer_points(Buffer)
        for buffer_point in buffer_points:
            color = colors[counter]
            if(color.startswith("FREE")): color = "pink"
            if(color[0] in ["C","D","U","L","R"]): color = "purple"
            buffer_point.setStyleSheet(f"background-color:{color}")
            counter+= 1
    
    def UpdateGUI(self,data):
        #Routers
        routers = data['routers']
        #Get the list of Routers
        #print(routers)
        for name in routers.keys():
            router = self.centralwidget.findChild(QWidget, f"{name}")
            for child in router.children():
                if(child.objectName()[:11] == "Buffer_DOWN"):
                    colors = self.Get_Colors(routers[name]['port_2'],routers[name]['port_3'])
                    self.Color_Buffers(child, colors)
                elif(child.objectName()[:11] == "Buffer_LEFT"):
                    colors = self.Get_Colors(routers[name]['port_4'],routers[name]['port_5'])
                    self.Color_Buffers(child, colors)
                elif(child.objectName()[:12] == "Buffer_RIGHT"):
                    colors = self.Get_Colors(routers[name]['port_8'],routers[name]['port_9'])
                    self.Color_Buffers(child, colors)
                elif(child.objectName()[:9] == "Buffer_UP"):
                    colors = self.Get_Colors(routers[name]['port_6'],routers[name]['port_7'])
                    self.Color_Buffers(child, colors)
                elif(child.objectName()[:12] == "Buffer_Slave"):
                    colors = self.Get_Colors(routers[name]['port_0'],routers[name]['port_1'])
                    self.Color_Buffers(child, colors)
        #This is a bodge, go over and make sure there is only one global clock tick
        self.clock_tick+= 1
        self.Timer.setText(f"Clock Tick: {self.clock_tick}")

    def keyPressEvent(self, event):
        if(event.key() == Qt.Key.Key_Space):
            self.UpdateGUI(getJSONGUI())
        if(event.key() == Qt.Key.Key_Q):
           self.widget_10.setStyleSheet(f"background-color: blue")
        if(event.key() == Qt.Key.Key_E):
            self.widget_10.setStyleSheet(f"background-color: purple")
        if(event.key() == Qt.Key.Key_Escape):
            self.Window.close()


def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Window(MainWindow)
    #keyboard.hook(ui.on_key_event)
    MainWindow.show()
    MainWindow.setWindowState(Qt.WindowFullScreen)
    sys.exit(app.exec_())
main()
