from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtGui import QKeyEvent
#from PyQt5.QtWidgets import QApplication,QMainWindow, QLabel, QVBoxLayout, QWidget, QPushButton, QHBoxLayout
#from PyQt5.QtGui import QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
import sys, keyboard
from copy import copy
from WORMHOLE import getJSONGUI

class Window(object):
    def __init__(self, MainWindow):
        self.Window = MainWindow

        #Paste UI Generated Code here
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: white")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Rout8 = QtWidgets.QWidget(self.centralwidget)
        self.Rout8.setGeometry(QtCore.QRect(410, 0, 301, 331))
        self.Rout8.setObjectName("Rout8")
        self.Buffer_DOWN = QtWidgets.QWidget(self.Rout8)
        self.Buffer_DOWN.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN.setObjectName("Buffer_DOWN")
        self.HighC = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighC.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC.setStyleSheet("background-color: green")
        self.HighC.setObjectName("HighC")
        self.HighB = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighB.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB.setStyleSheet("background-color: green")
        self.HighB.setObjectName("HighB")
        self.HighA = QtWidgets.QWidget(self.Buffer_DOWN)
        self.HighA.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA.setStyleSheet("background-color: green")
        self.HighA.setObjectName("HighA")
        self.LowC = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowC.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC.setStyleSheet("background-color: green")
        self.LowC.setObjectName("LowC")
        self.LowB = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowB.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB.setStyleSheet("background-color: green")
        self.LowB.setObjectName("LowB")
        self.LowA = QtWidgets.QWidget(self.Buffer_DOWN)
        self.LowA.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA.setStyleSheet("background-color: green")
        self.LowA.setObjectName("LowA")
        self.HighA.raise_()
        self.HighB.raise_()
        self.HighC.raise_()
        self.LowA.raise_()
        self.LowB.raise_()
        self.LowC.raise_()
        self.Buffer_UP = QtWidgets.QWidget(self.Rout8)
        self.Buffer_UP.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP.setObjectName("Buffer_UP")
        self.HighA_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighA_4.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_4.setStyleSheet("background-color: green")
        self.HighA_4.setObjectName("HighA_4")
        self.HighB_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighB_4.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_4.setStyleSheet("background-color: green")
        self.HighB_4.setObjectName("HighB_4")
        self.HighC_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.HighC_4.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_4.setStyleSheet("background-color: green")
        self.HighC_4.setObjectName("HighC_4")
        self.LowA_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowA_4.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_4.setStyleSheet("background-color: green")
        self.LowA_4.setObjectName("LowA_4")
        self.LowB_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowB_4.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_4.setStyleSheet("background-color: green")
        self.LowB_4.setObjectName("LowB_4")
        self.LowC_4 = QtWidgets.QWidget(self.Buffer_UP)
        self.LowC_4.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_4.setStyleSheet("background-color: green")
        self.LowC_4.setObjectName("LowC_4")
        self.label = QtWidgets.QLabel(self.Rout8)
        self.label.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label.setObjectName("label")
        self.Buffer_RIGHT = QtWidgets.QWidget(self.Rout8)
        self.Buffer_RIGHT.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT.setObjectName("Buffer_RIGHT")
        self.HighC_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighC_3.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_3.setStyleSheet("background-color: green")
        self.HighC_3.setObjectName("HighC_3")
        self.LowB_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowB_3.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_3.setStyleSheet("background-color: green")
        self.LowB_3.setObjectName("LowB_3")
        self.HighB_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighB_3.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_3.setStyleSheet("background-color: green")
        self.HighB_3.setObjectName("HighB_3")
        self.LowC_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowC_3.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_3.setStyleSheet("background-color: green")
        self.LowC_3.setObjectName("LowC_3")
        self.LowA_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.LowA_3.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_3.setStyleSheet("background-color: green")
        self.LowA_3.setObjectName("LowA_3")
        self.HighA_3 = QtWidgets.QWidget(self.Buffer_RIGHT)
        self.HighA_3.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_3.setStyleSheet("background-color: green")
        self.HighA_3.setObjectName("HighA_3")
        self.HighC_3.raise_()
        self.HighB_3.raise_()
        self.HighA_3.raise_()
        self.LowA_3.raise_()
        self.LowB_3.raise_()
        self.LowC_3.raise_()
        self.Buffer_LEFT = QtWidgets.QWidget(self.Rout8)
        self.Buffer_LEFT.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT.setObjectName("Buffer_LEFT")
        self.HighA_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighA_2.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_2.setStyleSheet("background-color: green")
        self.HighA_2.setObjectName("HighA_2")
        self.LowB_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowB_2.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_2.setStyleSheet("background-color: green")
        self.LowB_2.setObjectName("LowB_2")
        self.HighB_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighB_2.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_2.setStyleSheet("background-color: green")
        self.HighB_2.setObjectName("HighB_2")
        self.LowA_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowA_2.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_2.setStyleSheet("background-color: green")
        self.LowA_2.setObjectName("LowA_2")
        self.LowC_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.LowC_2.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_2.setStyleSheet("background-color: green")
        self.LowC_2.setObjectName("LowC_2")
        self.HighC_2 = QtWidgets.QWidget(self.Buffer_LEFT)
        self.HighC_2.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_2.setStyleSheet("background-color: green")
        self.HighC_2.setObjectName("HighC_2")
        self.Buffer_Slave = QtWidgets.QWidget(self.Rout8)
        self.Buffer_Slave.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave.setObjectName("Buffer_Slave")
        self.HighC_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighC_5.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_5.setStyleSheet("background-color: green")
        self.HighC_5.setObjectName("HighC_5")
        self.LowB_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowB_5.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_5.setStyleSheet("background-color: green")
        self.LowB_5.setObjectName("LowB_5")
        self.HighB_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighB_5.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_5.setStyleSheet("background-color: green")
        self.HighB_5.setObjectName("HighB_5")
        self.LowC_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowC_5.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_5.setStyleSheet("background-color: green")
        self.LowC_5.setObjectName("LowC_5")
        self.LowA_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.LowA_5.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_5.setStyleSheet("background-color: green")
        self.LowA_5.setObjectName("LowA_5")
        self.HighA_5 = QtWidgets.QWidget(self.Buffer_Slave)
        self.HighA_5.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_5.setStyleSheet("background-color: green")
        self.HighA_5.setObjectName("HighA_5")
        self.label.raise_()
        self.Buffer_DOWN.raise_()
        self.Buffer_UP.raise_()
        self.Buffer_RIGHT.raise_()
        self.Buffer_LEFT.raise_()
        self.Buffer_Slave.raise_()
        self.Router8_2 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_2.setGeometry(QtCore.QRect(800, 0, 291, 331))
        self.Router8_2.setObjectName("Router8_2")
        self.Buffer_DOWN_2 = QtWidgets.QWidget(self.Router8_2)
        self.Buffer_DOWN_2.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_2.setObjectName("Buffer_DOWN_2")
        self.widget_5 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.widget_5.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_5.setStyleSheet("background-color: green")
        self.widget_5.setObjectName("widget_5")
        self.widget_13 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.widget_13.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_13.setStyleSheet("background-color: green")
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.widget_14.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_14.setStyleSheet("background-color: green")
        self.widget_14.setObjectName("widget_14")
        self.widget_21 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.widget_21.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_21.setStyleSheet("background-color: green")
        self.widget_21.setObjectName("widget_21")
        self.widget_28 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.widget_28.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_28.setStyleSheet("background-color: green")
        self.widget_28.setObjectName("widget_28")
        self.High0_3 = QtWidgets.QWidget(self.Buffer_DOWN_2)
        self.High0_3.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_3.setStyleSheet("background-color: green")
        self.High0_3.setObjectName("High0_3")
        self.Buffer_UP_2 = QtWidgets.QWidget(self.Router8_2)
        self.Buffer_UP_2.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_2.setObjectName("Buffer_UP_2")
        self.widget_35 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_35.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_35.setStyleSheet("background-color: green")
        self.widget_35.setObjectName("widget_35")
        self.widget_36 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_36.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_36.setStyleSheet("background-color: green")
        self.widget_36.setObjectName("widget_36")
        self.widget_37 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_37.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_37.setStyleSheet("background-color: green")
        self.widget_37.setObjectName("widget_37")
        self.widget_38 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_38.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_38.setStyleSheet("background-color: green")
        self.widget_38.setObjectName("widget_38")
        self.widget_39 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_39.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_39.setStyleSheet("background-color: green")
        self.widget_39.setObjectName("widget_39")
        self.widget_40 = QtWidgets.QWidget(self.Buffer_UP_2)
        self.widget_40.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_40.setStyleSheet("background-color: green")
        self.widget_40.setObjectName("widget_40")
        self.label_2 = QtWidgets.QLabel(self.Router8_2)
        self.label_2.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_2.setObjectName("label_2")
        self.Buffer_RIGHT_2 = QtWidgets.QWidget(self.Router8_2)
        self.Buffer_RIGHT_2.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_2.setObjectName("Buffer_RIGHT_2")
        self.widget_41 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_41.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_41.setStyleSheet("background-color: green")
        self.widget_41.setObjectName("widget_41")
        self.widget_42 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_42.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_42.setStyleSheet("background-color: green")
        self.widget_42.setObjectName("widget_42")
        self.widget_43 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_43.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_43.setStyleSheet("background-color: green")
        self.widget_43.setObjectName("widget_43")
        self.widget_44 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_44.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_44.setStyleSheet("background-color: green")
        self.widget_44.setObjectName("widget_44")
        self.widget_45 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_45.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_45.setStyleSheet("background-color: green")
        self.widget_45.setObjectName("widget_45")
        self.widget_46 = QtWidgets.QWidget(self.Buffer_RIGHT_2)
        self.widget_46.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_46.setStyleSheet("background-color: green")
        self.widget_46.setObjectName("widget_46")
        self.Buffer_LEFT_2 = QtWidgets.QWidget(self.Router8_2)
        self.Buffer_LEFT_2.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_2.setObjectName("Buffer_LEFT_2")
        self.LEFTHigh0_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTHigh0_2.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_2.setStyleSheet("background-color: green")
        self.LEFTHigh0_2.setObjectName("LEFTHigh0_2")
        self.LEFTLow1_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTLow1_2.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_2.setStyleSheet("background-color: green")
        self.LEFTLow1_2.setObjectName("LEFTLow1_2")
        self.LEFTHigh1_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTHigh1_2.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_2.setStyleSheet("background-color: green")
        self.LEFTHigh1_2.setObjectName("LEFTHigh1_2")
        self.LEFTLow0_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTLow0_2.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_2.setStyleSheet("background-color: green")
        self.LEFTLow0_2.setObjectName("LEFTLow0_2")
        self.LEFTLow2_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTLow2_2.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_2.setStyleSheet("background-color: green")
        self.LEFTLow2_2.setObjectName("LEFTLow2_2")
        self.LEFTHigh2_2 = QtWidgets.QWidget(self.Buffer_LEFT_2)
        self.LEFTHigh2_2.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_2.setStyleSheet("background-color: green")
        self.LEFTHigh2_2.setObjectName("LEFTHigh2_2")
        self.label_2.raise_()
        self.Buffer_DOWN_2.raise_()
        self.Buffer_UP_2.raise_()
        self.Buffer_RIGHT_2.raise_()
        self.Buffer_LEFT_2.raise_()
        self.Router8_4 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_4.setGeometry(QtCore.QRect(800, 360, 291, 331))
        self.Router8_4.setObjectName("Router8_4")
        self.Buffer_DOWN_4 = QtWidgets.QWidget(self.Router8_4)
        self.Buffer_DOWN_4.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_4.setObjectName("Buffer_DOWN_4")
        self.widget_7 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.widget_7.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_7.setStyleSheet("background-color: green")
        self.widget_7.setObjectName("widget_7")
        self.widget_29 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.widget_29.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_29.setStyleSheet("background-color: green")
        self.widget_29.setObjectName("widget_29")
        self.widget_30 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.widget_30.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_30.setStyleSheet("background-color: green")
        self.widget_30.setObjectName("widget_30")
        self.widget_31 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.widget_31.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_31.setStyleSheet("background-color: green")
        self.widget_31.setObjectName("widget_31")
        self.widget_32 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.widget_32.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_32.setStyleSheet("background-color: green")
        self.widget_32.setObjectName("widget_32")
        self.High0_5 = QtWidgets.QWidget(self.Buffer_DOWN_4)
        self.High0_5.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_5.setStyleSheet("background-color: green")
        self.High0_5.setObjectName("High0_5")
        self.Buffer_UP_4 = QtWidgets.QWidget(self.Router8_4)
        self.Buffer_UP_4.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_4.setObjectName("Buffer_UP_4")
        self.widget_64 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_64.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_64.setStyleSheet("background-color: green")
        self.widget_64.setObjectName("widget_64")
        self.widget_65 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_65.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_65.setStyleSheet("background-color: green")
        self.widget_65.setObjectName("widget_65")
        self.widget_66 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_66.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_66.setStyleSheet("background-color: green")
        self.widget_66.setObjectName("widget_66")
        self.widget_67 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_67.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_67.setStyleSheet("background-color: green")
        self.widget_67.setObjectName("widget_67")
        self.widget_68 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_68.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_68.setStyleSheet("background-color: green")
        self.widget_68.setObjectName("widget_68")
        self.widget_69 = QtWidgets.QWidget(self.Buffer_UP_4)
        self.widget_69.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_69.setStyleSheet("background-color: green")
        self.widget_69.setObjectName("widget_69")
        self.label_4 = QtWidgets.QLabel(self.Router8_4)
        self.label_4.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_4.setObjectName("label_4")
        self.Buffer_RIGHT_4 = QtWidgets.QWidget(self.Router8_4)
        self.Buffer_RIGHT_4.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_4.setObjectName("Buffer_RIGHT_4")
        self.widget_70 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_70.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_70.setStyleSheet("background-color: green")
        self.widget_70.setObjectName("widget_70")
        self.widget_71 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_71.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_71.setStyleSheet("background-color: green")
        self.widget_71.setObjectName("widget_71")
        self.widget_72 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_72.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_72.setStyleSheet("background-color: green")
        self.widget_72.setObjectName("widget_72")
        self.widget_73 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_73.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_73.setStyleSheet("background-color: green")
        self.widget_73.setObjectName("widget_73")
        self.widget_74 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_74.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_74.setStyleSheet("background-color: green")
        self.widget_74.setObjectName("widget_74")
        self.widget_75 = QtWidgets.QWidget(self.Buffer_RIGHT_4)
        self.widget_75.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_75.setStyleSheet("background-color: green")
        self.widget_75.setObjectName("widget_75")
        self.Buffer_LEFT_4 = QtWidgets.QWidget(self.Router8_4)
        self.Buffer_LEFT_4.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_4.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_4.setObjectName("Buffer_LEFT_4")
        self.LEFTHigh0_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTHigh0_4.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_4.setStyleSheet("background-color: green")
        self.LEFTHigh0_4.setObjectName("LEFTHigh0_4")
        self.LEFTLow1_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTLow1_4.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_4.setStyleSheet("background-color: green")
        self.LEFTLow1_4.setObjectName("LEFTLow1_4")
        self.LEFTHigh1_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTHigh1_4.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_4.setStyleSheet("background-color: green")
        self.LEFTHigh1_4.setObjectName("LEFTHigh1_4")
        self.LEFTLow0_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTLow0_4.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_4.setStyleSheet("background-color: green")
        self.LEFTLow0_4.setObjectName("LEFTLow0_4")
        self.LEFTLow2_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTLow2_4.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_4.setStyleSheet("background-color: green")
        self.LEFTLow2_4.setObjectName("LEFTLow2_4")
        self.LEFTHigh2_4 = QtWidgets.QWidget(self.Buffer_LEFT_4)
        self.LEFTHigh2_4.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_4.setStyleSheet("background-color: green")
        self.LEFTHigh2_4.setObjectName("LEFTHigh2_4")
        self.label_4.raise_()
        self.Buffer_DOWN_4.raise_()
        self.Buffer_UP_4.raise_()
        self.Buffer_RIGHT_4.raise_()
        self.Buffer_LEFT_4.raise_()
        self.Router8_5 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_5.setGeometry(QtCore.QRect(799, 720, 301, 331))
        self.Router8_5.setObjectName("Router8_5")
        self.Buffer_DOWN_6 = QtWidgets.QWidget(self.Router8_5)
        self.Buffer_DOWN_6.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_6.setObjectName("Buffer_DOWN_6")
        self.widget_86 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.widget_86.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_86.setStyleSheet("background-color: green")
        self.widget_86.setObjectName("widget_86")
        self.widget_87 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.widget_87.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_87.setStyleSheet("background-color: green")
        self.widget_87.setObjectName("widget_87")
        self.widget_88 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.widget_88.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_88.setStyleSheet("background-color: green")
        self.widget_88.setObjectName("widget_88")
        self.widget_89 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.widget_89.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_89.setStyleSheet("background-color: green")
        self.widget_89.setObjectName("widget_89")
        self.widget_90 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.widget_90.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_90.setStyleSheet("background-color: green")
        self.widget_90.setObjectName("widget_90")
        self.High0_7 = QtWidgets.QWidget(self.Buffer_DOWN_6)
        self.High0_7.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_7.setStyleSheet("background-color: green")
        self.High0_7.setObjectName("High0_7")
        self.Buffer_UP_6 = QtWidgets.QWidget(self.Router8_5)
        self.Buffer_UP_6.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_6.setObjectName("Buffer_UP_6")
        self.widget_91 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_91.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_91.setStyleSheet("background-color: green")
        self.widget_91.setObjectName("widget_91")
        self.widget_92 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_92.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_92.setStyleSheet("background-color: green")
        self.widget_92.setObjectName("widget_92")
        self.widget_93 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_93.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_93.setStyleSheet("background-color: green")
        self.widget_93.setObjectName("widget_93")
        self.widget_94 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_94.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_94.setStyleSheet("background-color: green")
        self.widget_94.setObjectName("widget_94")
        self.widget_95 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_95.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_95.setStyleSheet("background-color: green")
        self.widget_95.setObjectName("widget_95")
        self.widget_96 = QtWidgets.QWidget(self.Buffer_UP_6)
        self.widget_96.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_96.setStyleSheet("background-color: green")
        self.widget_96.setObjectName("widget_96")
        self.label_6 = QtWidgets.QLabel(self.Router8_5)
        self.label_6.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_6.setObjectName("label_6")
        self.Buffer_RIGHT_6 = QtWidgets.QWidget(self.Router8_5)
        self.Buffer_RIGHT_6.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_6.setObjectName("Buffer_RIGHT_6")
        self.widget_97 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_97.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_97.setStyleSheet("background-color: green")
        self.widget_97.setObjectName("widget_97")
        self.widget_98 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_98.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_98.setStyleSheet("background-color: green")
        self.widget_98.setObjectName("widget_98")
        self.widget_99 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_99.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_99.setStyleSheet("background-color: green")
        self.widget_99.setObjectName("widget_99")
        self.widget_100 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_100.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_100.setStyleSheet("background-color: green")
        self.widget_100.setObjectName("widget_100")
        self.widget_101 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_101.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_101.setStyleSheet("background-color: green")
        self.widget_101.setObjectName("widget_101")
        self.widget_102 = QtWidgets.QWidget(self.Buffer_RIGHT_6)
        self.widget_102.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_102.setStyleSheet("background-color: green")
        self.widget_102.setObjectName("widget_102")
        self.Buffer_LEFT_6 = QtWidgets.QWidget(self.Router8_5)
        self.Buffer_LEFT_6.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_6.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_6.setObjectName("Buffer_LEFT_6")
        self.LEFTHigh0_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTHigh0_6.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_6.setStyleSheet("background-color: green")
        self.LEFTHigh0_6.setObjectName("LEFTHigh0_6")
        self.LEFTLow1_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTLow1_6.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_6.setStyleSheet("background-color: green")
        self.LEFTLow1_6.setObjectName("LEFTLow1_6")
        self.LEFTHigh1_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTHigh1_6.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_6.setStyleSheet("background-color: green")
        self.LEFTHigh1_6.setObjectName("LEFTHigh1_6")
        self.LEFTLow0_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTLow0_6.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_6.setStyleSheet("background-color: green")
        self.LEFTLow0_6.setObjectName("LEFTLow0_6")
        self.LEFTLow2_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTLow2_6.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_6.setStyleSheet("background-color: green")
        self.LEFTLow2_6.setObjectName("LEFTLow2_6")
        self.LEFTHigh2_6 = QtWidgets.QWidget(self.Buffer_LEFT_6)
        self.LEFTHigh2_6.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_6.setStyleSheet("background-color: green")
        self.LEFTHigh2_6.setObjectName("LEFTHigh2_6")
        self.Buffer_Slave_3 = QtWidgets.QWidget(self.Router8_5)
        self.Buffer_Slave_3.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_3.setObjectName("Buffer_Slave_3")
        self.widget_143 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_143.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.widget_143.setStyleSheet("background-color: green")
        self.widget_143.setObjectName("widget_143")
        self.widget_144 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_144.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.widget_144.setStyleSheet("background-color: green")
        self.widget_144.setObjectName("widget_144")
        self.widget_145 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_145.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.widget_145.setStyleSheet("background-color: green")
        self.widget_145.setObjectName("widget_145")
        self.widget_146 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_146.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.widget_146.setStyleSheet("background-color: green")
        self.widget_146.setObjectName("widget_146")
        self.widget_147 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_147.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.widget_147.setStyleSheet("background-color: green")
        self.widget_147.setObjectName("widget_147")
        self.widget_148 = QtWidgets.QWidget(self.Buffer_Slave_3)
        self.widget_148.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.widget_148.setStyleSheet("background-color: green")
        self.widget_148.setObjectName("widget_148")
        self.label_6.raise_()
        self.Buffer_DOWN_6.raise_()
        self.Buffer_UP_6.raise_()
        self.Buffer_RIGHT_6.raise_()
        self.Buffer_LEFT_6.raise_()
        self.Buffer_Slave_3.raise_()
        self.Router8_6 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_6.setGeometry(QtCore.QRect(1191, 0, 301, 331))
        self.Router8_6.setObjectName("Router8_6")
        self.Buffer_DOWN_9 = QtWidgets.QWidget(self.Router8_6)
        self.Buffer_DOWN_9.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_9.setObjectName("Buffer_DOWN_9")
        self.widget_173 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.widget_173.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_173.setStyleSheet("background-color: green")
        self.widget_173.setObjectName("widget_173")
        self.widget_174 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.widget_174.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_174.setStyleSheet("background-color: green")
        self.widget_174.setObjectName("widget_174")
        self.widget_175 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.widget_175.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_175.setStyleSheet("background-color: green")
        self.widget_175.setObjectName("widget_175")
        self.widget_176 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.widget_176.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_176.setStyleSheet("background-color: green")
        self.widget_176.setObjectName("widget_176")
        self.widget_177 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.widget_177.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_177.setStyleSheet("background-color: green")
        self.widget_177.setObjectName("widget_177")
        self.High0_10 = QtWidgets.QWidget(self.Buffer_DOWN_9)
        self.High0_10.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_10.setStyleSheet("background-color: green")
        self.High0_10.setObjectName("High0_10")
        self.Buffer_UP_9 = QtWidgets.QWidget(self.Router8_6)
        self.Buffer_UP_9.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_9.setObjectName("Buffer_UP_9")
        self.widget_178 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_178.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_178.setStyleSheet("background-color: green")
        self.widget_178.setObjectName("widget_178")
        self.widget_179 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_179.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_179.setStyleSheet("background-color: green")
        self.widget_179.setObjectName("widget_179")
        self.widget_180 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_180.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_180.setStyleSheet("background-color: green")
        self.widget_180.setObjectName("widget_180")
        self.widget_181 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_181.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_181.setStyleSheet("background-color: green")
        self.widget_181.setObjectName("widget_181")
        self.widget_182 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_182.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_182.setStyleSheet("background-color: green")
        self.widget_182.setObjectName("widget_182")
        self.widget_183 = QtWidgets.QWidget(self.Buffer_UP_9)
        self.widget_183.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_183.setStyleSheet("background-color: green")
        self.widget_183.setObjectName("widget_183")
        self.label_9 = QtWidgets.QLabel(self.Router8_6)
        self.label_9.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_9.setObjectName("label_9")
        self.Buffer_RIGHT_9 = QtWidgets.QWidget(self.Router8_6)
        self.Buffer_RIGHT_9.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_9.setObjectName("Buffer_RIGHT_9")
        self.widget_184 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_184.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_184.setStyleSheet("background-color: green")
        self.widget_184.setObjectName("widget_184")
        self.widget_185 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_185.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_185.setStyleSheet("background-color: green")
        self.widget_185.setObjectName("widget_185")
        self.widget_186 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_186.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_186.setStyleSheet("background-color: green")
        self.widget_186.setObjectName("widget_186")
        self.widget_187 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_187.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_187.setStyleSheet("background-color: green")
        self.widget_187.setObjectName("widget_187")
        self.widget_188 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_188.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_188.setStyleSheet("background-color: green")
        self.widget_188.setObjectName("widget_188")
        self.widget_189 = QtWidgets.QWidget(self.Buffer_RIGHT_9)
        self.widget_189.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_189.setStyleSheet("background-color: green")
        self.widget_189.setObjectName("widget_189")
        self.Buffer_LEFT_9 = QtWidgets.QWidget(self.Router8_6)
        self.Buffer_LEFT_9.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_9.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_9.setObjectName("Buffer_LEFT_9")
        self.LEFTHigh0_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTHigh0_9.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_9.setStyleSheet("background-color: green")
        self.LEFTHigh0_9.setObjectName("LEFTHigh0_9")
        self.LEFTLow1_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTLow1_9.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_9.setStyleSheet("background-color: green")
        self.LEFTLow1_9.setObjectName("LEFTLow1_9")
        self.LEFTHigh1_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTHigh1_9.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_9.setStyleSheet("background-color: green")
        self.LEFTHigh1_9.setObjectName("LEFTHigh1_9")
        self.LEFTLow0_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTLow0_9.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_9.setStyleSheet("background-color: green")
        self.LEFTLow0_9.setObjectName("LEFTLow0_9")
        self.LEFTLow2_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTLow2_9.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_9.setStyleSheet("background-color: green")
        self.LEFTLow2_9.setObjectName("LEFTLow2_9")
        self.LEFTHigh2_9 = QtWidgets.QWidget(self.Buffer_LEFT_9)
        self.LEFTHigh2_9.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_9.setStyleSheet("background-color: green")
        self.LEFTHigh2_9.setObjectName("LEFTHigh2_9")
        self.Buffer_Slave_7 = QtWidgets.QWidget(self.Router8_6)
        self.Buffer_Slave_7.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_7.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_7.setObjectName("Buffer_Slave_7")
        self.widget_190 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_190.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.widget_190.setStyleSheet("background-color: green")
        self.widget_190.setObjectName("widget_190")
        self.widget_191 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_191.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.widget_191.setStyleSheet("background-color: green")
        self.widget_191.setObjectName("widget_191")
        self.widget_192 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_192.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.widget_192.setStyleSheet("background-color: green")
        self.widget_192.setObjectName("widget_192")
        self.widget_193 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_193.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.widget_193.setStyleSheet("background-color: green")
        self.widget_193.setObjectName("widget_193")
        self.widget_194 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_194.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.widget_194.setStyleSheet("background-color: green")
        self.widget_194.setObjectName("widget_194")
        self.widget_195 = QtWidgets.QWidget(self.Buffer_Slave_7)
        self.widget_195.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.widget_195.setStyleSheet("background-color: green")
        self.widget_195.setObjectName("widget_195")
        self.label_9.raise_()
        self.Buffer_DOWN_9.raise_()
        self.Buffer_UP_9.raise_()
        self.Buffer_RIGHT_9.raise_()
        self.Buffer_LEFT_9.raise_()
        self.Buffer_Slave_7.raise_()
        self.Router8_7 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_7.setGeometry(QtCore.QRect(1191, 360, 301, 331))
        self.Router8_7.setObjectName("Router8_7")
        self.Buffer_DOWN_10 = QtWidgets.QWidget(self.Router8_7)
        self.Buffer_DOWN_10.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_10.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_10.setObjectName("Buffer_DOWN_10")
        self.widget_196 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.widget_196.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_196.setStyleSheet("background-color: green")
        self.widget_196.setObjectName("widget_196")
        self.widget_197 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.widget_197.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_197.setStyleSheet("background-color: green")
        self.widget_197.setObjectName("widget_197")
        self.widget_198 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.widget_198.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_198.setStyleSheet("background-color: green")
        self.widget_198.setObjectName("widget_198")
        self.widget_199 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.widget_199.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_199.setStyleSheet("background-color: green")
        self.widget_199.setObjectName("widget_199")
        self.widget_200 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.widget_200.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_200.setStyleSheet("background-color: green")
        self.widget_200.setObjectName("widget_200")
        self.High0_11 = QtWidgets.QWidget(self.Buffer_DOWN_10)
        self.High0_11.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_11.setStyleSheet("background-color: green")
        self.High0_11.setObjectName("High0_11")
        self.Buffer_UP_10 = QtWidgets.QWidget(self.Router8_7)
        self.Buffer_UP_10.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_10.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_10.setObjectName("Buffer_UP_10")
        self.widget_201 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_201.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_201.setStyleSheet("background-color: green")
        self.widget_201.setObjectName("widget_201")
        self.widget_202 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_202.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_202.setStyleSheet("background-color: green")
        self.widget_202.setObjectName("widget_202")
        self.widget_203 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_203.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_203.setStyleSheet("background-color: green")
        self.widget_203.setObjectName("widget_203")
        self.widget_204 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_204.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_204.setStyleSheet("background-color: green")
        self.widget_204.setObjectName("widget_204")
        self.widget_205 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_205.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_205.setStyleSheet("background-color: green")
        self.widget_205.setObjectName("widget_205")
        self.widget_206 = QtWidgets.QWidget(self.Buffer_UP_10)
        self.widget_206.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_206.setStyleSheet("background-color: green")
        self.widget_206.setObjectName("widget_206")
        self.label_10 = QtWidgets.QLabel(self.Router8_7)
        self.label_10.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_10.setObjectName("label_10")
        self.Buffer_RIGHT_10 = QtWidgets.QWidget(self.Router8_7)
        self.Buffer_RIGHT_10.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_10.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_10.setObjectName("Buffer_RIGHT_10")
        self.widget_207 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_207.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_207.setStyleSheet("background-color: green")
        self.widget_207.setObjectName("widget_207")
        self.widget_208 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_208.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_208.setStyleSheet("background-color: green")
        self.widget_208.setObjectName("widget_208")
        self.widget_209 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_209.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_209.setStyleSheet("background-color: green")
        self.widget_209.setObjectName("widget_209")
        self.widget_210 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_210.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_210.setStyleSheet("background-color: green")
        self.widget_210.setObjectName("widget_210")
        self.widget_211 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_211.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_211.setStyleSheet("background-color: green")
        self.widget_211.setObjectName("widget_211")
        self.widget_212 = QtWidgets.QWidget(self.Buffer_RIGHT_10)
        self.widget_212.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_212.setStyleSheet("background-color: green")
        self.widget_212.setObjectName("widget_212")
        self.Buffer_LEFT_10 = QtWidgets.QWidget(self.Router8_7)
        self.Buffer_LEFT_10.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_10.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_10.setObjectName("Buffer_LEFT_10")
        self.LEFTHigh0_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTHigh0_10.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_10.setStyleSheet("background-color: green")
        self.LEFTHigh0_10.setObjectName("LEFTHigh0_10")
        self.LEFTLow1_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTLow1_10.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_10.setStyleSheet("background-color: green")
        self.LEFTLow1_10.setObjectName("LEFTLow1_10")
        self.LEFTHigh1_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTHigh1_10.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_10.setStyleSheet("background-color: green")
        self.LEFTHigh1_10.setObjectName("LEFTHigh1_10")
        self.LEFTLow0_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTLow0_10.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_10.setStyleSheet("background-color: green")
        self.LEFTLow0_10.setObjectName("LEFTLow0_10")
        self.LEFTLow2_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTLow2_10.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_10.setStyleSheet("background-color: green")
        self.LEFTLow2_10.setObjectName("LEFTLow2_10")
        self.LEFTHigh2_10 = QtWidgets.QWidget(self.Buffer_LEFT_10)
        self.LEFTHigh2_10.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_10.setStyleSheet("background-color: green")
        self.LEFTHigh2_10.setObjectName("LEFTHigh2_10")
        self.Buffer_Slave_8 = QtWidgets.QWidget(self.Router8_7)
        self.Buffer_Slave_8.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_8.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_8.setObjectName("Buffer_Slave_8")
        self.widget_213 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_213.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.widget_213.setStyleSheet("background-color: green")
        self.widget_213.setObjectName("widget_213")
        self.widget_214 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_214.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.widget_214.setStyleSheet("background-color: green")
        self.widget_214.setObjectName("widget_214")
        self.widget_215 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_215.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.widget_215.setStyleSheet("background-color: green")
        self.widget_215.setObjectName("widget_215")
        self.widget_216 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_216.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.widget_216.setStyleSheet("background-color: green")
        self.widget_216.setObjectName("widget_216")
        self.widget_217 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_217.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.widget_217.setStyleSheet("background-color: green")
        self.widget_217.setObjectName("widget_217")
        self.widget_218 = QtWidgets.QWidget(self.Buffer_Slave_8)
        self.widget_218.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.widget_218.setStyleSheet("background-color: green")
        self.widget_218.setObjectName("widget_218")
        self.label_10.raise_()
        self.Buffer_DOWN_10.raise_()
        self.Buffer_UP_10.raise_()
        self.Buffer_RIGHT_10.raise_()
        self.Buffer_LEFT_10.raise_()
        self.Buffer_Slave_8.raise_()
        self.Router8_8 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_8.setGeometry(QtCore.QRect(409, 720, 291, 331))
        self.Router8_8.setObjectName("Router8_8")
        self.Buffer_DOWN_12 = QtWidgets.QWidget(self.Router8_8)
        self.Buffer_DOWN_12.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_12.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_12.setObjectName("Buffer_DOWN_12")
        self.widget_236 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.widget_236.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_236.setStyleSheet("background-color: green")
        self.widget_236.setObjectName("widget_236")
        self.widget_237 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.widget_237.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_237.setStyleSheet("background-color: green")
        self.widget_237.setObjectName("widget_237")
        self.widget_238 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.widget_238.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_238.setStyleSheet("background-color: green")
        self.widget_238.setObjectName("widget_238")
        self.widget_239 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.widget_239.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_239.setStyleSheet("background-color: green")
        self.widget_239.setObjectName("widget_239")
        self.widget_240 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.widget_240.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_240.setStyleSheet("background-color: green")
        self.widget_240.setObjectName("widget_240")
        self.High0_13 = QtWidgets.QWidget(self.Buffer_DOWN_12)
        self.High0_13.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_13.setStyleSheet("background-color: green")
        self.High0_13.setObjectName("High0_13")
        self.Buffer_UP_12 = QtWidgets.QWidget(self.Router8_8)
        self.Buffer_UP_12.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_12.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_12.setObjectName("Buffer_UP_12")
        self.widget_241 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_241.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_241.setStyleSheet("background-color: green")
        self.widget_241.setObjectName("widget_241")
        self.widget_242 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_242.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_242.setStyleSheet("background-color: green")
        self.widget_242.setObjectName("widget_242")
        self.widget_243 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_243.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_243.setStyleSheet("background-color: green")
        self.widget_243.setObjectName("widget_243")
        self.widget_244 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_244.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_244.setStyleSheet("background-color: green")
        self.widget_244.setObjectName("widget_244")
        self.widget_245 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_245.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_245.setStyleSheet("background-color: green")
        self.widget_245.setObjectName("widget_245")
        self.widget_246 = QtWidgets.QWidget(self.Buffer_UP_12)
        self.widget_246.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_246.setStyleSheet("background-color: green")
        self.widget_246.setObjectName("widget_246")
        self.label_12 = QtWidgets.QLabel(self.Router8_8)
        self.label_12.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_12.setObjectName("label_12")
        self.Buffer_RIGHT_12 = QtWidgets.QWidget(self.Router8_8)
        self.Buffer_RIGHT_12.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_12.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_12.setObjectName("Buffer_RIGHT_12")
        self.widget_247 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_247.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_247.setStyleSheet("background-color: green")
        self.widget_247.setObjectName("widget_247")
        self.widget_248 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_248.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_248.setStyleSheet("background-color: green")
        self.widget_248.setObjectName("widget_248")
        self.widget_249 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_249.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_249.setStyleSheet("background-color: green")
        self.widget_249.setObjectName("widget_249")
        self.widget_250 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_250.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_250.setStyleSheet("background-color: green")
        self.widget_250.setObjectName("widget_250")
        self.widget_251 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_251.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_251.setStyleSheet("background-color: green")
        self.widget_251.setObjectName("widget_251")
        self.widget_252 = QtWidgets.QWidget(self.Buffer_RIGHT_12)
        self.widget_252.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_252.setStyleSheet("background-color: green")
        self.widget_252.setObjectName("widget_252")
        self.Buffer_LEFT_12 = QtWidgets.QWidget(self.Router8_8)
        self.Buffer_LEFT_12.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_12.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_12.setObjectName("Buffer_LEFT_12")
        self.LEFTHigh0_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTHigh0_12.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_12.setStyleSheet("background-color: green")
        self.LEFTHigh0_12.setObjectName("LEFTHigh0_12")
        self.LEFTLow1_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTLow1_12.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_12.setStyleSheet("background-color: green")
        self.LEFTLow1_12.setObjectName("LEFTLow1_12")
        self.LEFTHigh1_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTHigh1_12.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_12.setStyleSheet("background-color: green")
        self.LEFTHigh1_12.setObjectName("LEFTHigh1_12")
        self.LEFTLow0_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTLow0_12.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_12.setStyleSheet("background-color: green")
        self.LEFTLow0_12.setObjectName("LEFTLow0_12")
        self.LEFTLow2_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTLow2_12.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_12.setStyleSheet("background-color: green")
        self.LEFTLow2_12.setObjectName("LEFTLow2_12")
        self.LEFTHigh2_12 = QtWidgets.QWidget(self.Buffer_LEFT_12)
        self.LEFTHigh2_12.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_12.setStyleSheet("background-color: green")
        self.LEFTHigh2_12.setObjectName("LEFTHigh2_12")
        self.label_12.raise_()
        self.Buffer_DOWN_12.raise_()
        self.Buffer_UP_12.raise_()
        self.Buffer_RIGHT_12.raise_()
        self.Buffer_LEFT_12.raise_()
        self.Router8_9 = QtWidgets.QWidget(self.centralwidget)
        self.Router8_9.setGeometry(QtCore.QRect(1192, 720, 291, 331))
        self.Router8_9.setObjectName("Router8_9")
        self.Buffer_DOWN_13 = QtWidgets.QWidget(self.Router8_9)
        self.Buffer_DOWN_13.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_13.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_13.setObjectName("Buffer_DOWN_13")
        self.widget_253 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.widget_253.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_253.setStyleSheet("background-color: green")
        self.widget_253.setObjectName("widget_253")
        self.widget_254 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.widget_254.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_254.setStyleSheet("background-color: green")
        self.widget_254.setObjectName("widget_254")
        self.widget_255 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.widget_255.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_255.setStyleSheet("background-color: green")
        self.widget_255.setObjectName("widget_255")
        self.widget_256 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.widget_256.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_256.setStyleSheet("background-color: green")
        self.widget_256.setObjectName("widget_256")
        self.widget_257 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.widget_257.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_257.setStyleSheet("background-color: green")
        self.widget_257.setObjectName("widget_257")
        self.High0_14 = QtWidgets.QWidget(self.Buffer_DOWN_13)
        self.High0_14.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.High0_14.setStyleSheet("background-color: green")
        self.High0_14.setObjectName("High0_14")
        self.Buffer_UP_13 = QtWidgets.QWidget(self.Router8_9)
        self.Buffer_UP_13.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_13.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_13.setObjectName("Buffer_UP_13")
        self.widget_258 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_258.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.widget_258.setStyleSheet("background-color: green")
        self.widget_258.setObjectName("widget_258")
        self.widget_259 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_259.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.widget_259.setStyleSheet("background-color: green")
        self.widget_259.setObjectName("widget_259")
        self.widget_260 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_260.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.widget_260.setStyleSheet("background-color: green")
        self.widget_260.setObjectName("widget_260")
        self.widget_261 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_261.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.widget_261.setStyleSheet("background-color: green")
        self.widget_261.setObjectName("widget_261")
        self.widget_262 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_262.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.widget_262.setStyleSheet("background-color: green")
        self.widget_262.setObjectName("widget_262")
        self.widget_263 = QtWidgets.QWidget(self.Buffer_UP_13)
        self.widget_263.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_263.setStyleSheet("background-color: green")
        self.widget_263.setObjectName("widget_263")
        self.label_13 = QtWidgets.QLabel(self.Router8_9)
        self.label_13.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Images/Consumer_Router.png"))
        self.label_13.setObjectName("label_13")
        self.Buffer_RIGHT_13 = QtWidgets.QWidget(self.Router8_9)
        self.Buffer_RIGHT_13.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_13.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_13.setObjectName("Buffer_RIGHT_13")
        self.widget_264 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_264.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.widget_264.setStyleSheet("background-color: green")
        self.widget_264.setObjectName("widget_264")
        self.widget_265 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_265.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.widget_265.setStyleSheet("background-color: green")
        self.widget_265.setObjectName("widget_265")
        self.widget_266 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_266.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.widget_266.setStyleSheet("background-color: green")
        self.widget_266.setObjectName("widget_266")
        self.widget_267 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_267.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.widget_267.setStyleSheet("background-color: green")
        self.widget_267.setObjectName("widget_267")
        self.widget_268 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_268.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.widget_268.setStyleSheet("background-color: green")
        self.widget_268.setObjectName("widget_268")
        self.widget_269 = QtWidgets.QWidget(self.Buffer_RIGHT_13)
        self.widget_269.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.widget_269.setStyleSheet("background-color: green")
        self.widget_269.setObjectName("widget_269")
        self.Buffer_LEFT_13 = QtWidgets.QWidget(self.Router8_9)
        self.Buffer_LEFT_13.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_13.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_13.setObjectName("Buffer_LEFT_13")
        self.LEFTHigh0_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTHigh0_13.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.LEFTHigh0_13.setStyleSheet("background-color: green")
        self.LEFTHigh0_13.setObjectName("LEFTHigh0_13")
        self.LEFTLow1_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTLow1_13.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LEFTLow1_13.setStyleSheet("background-color: green")
        self.LEFTLow1_13.setObjectName("LEFTLow1_13")
        self.LEFTHigh1_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTHigh1_13.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.LEFTHigh1_13.setStyleSheet("background-color: green")
        self.LEFTHigh1_13.setObjectName("LEFTHigh1_13")
        self.LEFTLow0_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTLow0_13.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LEFTLow0_13.setStyleSheet("background-color: green")
        self.LEFTLow0_13.setObjectName("LEFTLow0_13")
        self.LEFTLow2_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTLow2_13.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LEFTLow2_13.setStyleSheet("background-color: green")
        self.LEFTLow2_13.setObjectName("LEFTLow2_13")
        self.LEFTHigh2_13 = QtWidgets.QWidget(self.Buffer_LEFT_13)
        self.LEFTHigh2_13.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LEFTHigh2_13.setStyleSheet("background-color: green")
        self.LEFTHigh2_13.setObjectName("LEFTHigh2_13")
        self.label_13.raise_()
        self.Buffer_DOWN_13.raise_()
        self.Buffer_UP_13.raise_()
        self.Buffer_RIGHT_13.raise_()
        self.Buffer_LEFT_13.raise_()
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(550, 281, 10, 114))
        self.widget_8.setStyleSheet("background-color: black")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(940, 281, 10, 114))
        self.widget_9.setStyleSheet("background-color: black")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(1332, 281, 10, 114))
        self.widget_10.setStyleSheet("background-color: black")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(1332, 641, 10, 114))
        self.widget_11.setStyleSheet("background-color: black")
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(940, 641, 10, 114))
        self.widget_12.setStyleSheet("background-color: black")
        self.widget_12.setObjectName("widget_12")
        self.widget_33 = QtWidgets.QWidget(self.centralwidget)
        self.widget_33.setGeometry(QtCore.QRect(550, 641, 10, 114))
        self.widget_33.setStyleSheet("background-color: black")
        self.widget_33.setObjectName("widget_33")
        self.widget_34 = QtWidgets.QWidget(self.centralwidget)
        self.widget_34.setGeometry(QtCore.QRect(680, 153, 140, 10))
        self.widget_34.setStyleSheet("background-color: black")
        self.widget_34.setObjectName("widget_34")
        self.widget_47 = QtWidgets.QWidget(self.centralwidget)
        self.widget_47.setGeometry(QtCore.QRect(680, 513, 140, 10))
        self.widget_47.setStyleSheet("background-color: black")
        self.widget_47.setObjectName("widget_47")
        self.widget_48 = QtWidgets.QWidget(self.centralwidget)
        self.widget_48.setGeometry(QtCore.QRect(679, 874, 140, 10))
        self.widget_48.setStyleSheet("background-color: black")
        self.widget_48.setObjectName("widget_48")
        self.widget_49 = QtWidgets.QWidget(self.centralwidget)
        self.widget_49.setGeometry(QtCore.QRect(1069, 874, 144, 10))
        self.widget_49.setStyleSheet("background-color: black")
        self.widget_49.setObjectName("widget_49")
        self.widget_50 = QtWidgets.QWidget(self.centralwidget)
        self.widget_50.setGeometry(QtCore.QRect(1070, 513, 142, 10))
        self.widget_50.setStyleSheet("background-color: black")
        self.widget_50.setObjectName("widget_50")
        self.widget_51 = QtWidgets.QWidget(self.centralwidget)
        self.widget_51.setGeometry(QtCore.QRect(1070, 153, 142, 10))
        self.widget_51.setStyleSheet("background-color: black")
        self.widget_51.setObjectName("widget_51")
        self.Rout7 = QtWidgets.QWidget(self.centralwidget)
        self.Rout7.setGeometry(QtCore.QRect(409, 360, 301, 331))
        self.Rout7.setObjectName("Rout7")
        self.Buffer_DOWN_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_DOWN_3.setGeometry(QtCore.QRect(97, 206, 81, 80))
        self.Buffer_DOWN_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_DOWN_3.setObjectName("Buffer_DOWN_3")
        self.HighC_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighC_6.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighC_6.setStyleSheet("background-color: green")
        self.HighC_6.setObjectName("HighC_6")
        self.HighB_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighB_6.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_6.setStyleSheet("background-color: green")
        self.HighB_6.setObjectName("HighB_6")
        self.HighA_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.HighA_6.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighA_6.setStyleSheet("background-color: green")
        self.HighA_6.setObjectName("HighA_6")
        self.LowC_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowC_6.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowC_6.setStyleSheet("background-color: green")
        self.LowC_6.setObjectName("LowC_6")
        self.LowB_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowB_6.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_6.setStyleSheet("background-color: green")
        self.LowB_6.setObjectName("LowB_6")
        self.LowA_6 = QtWidgets.QWidget(self.Buffer_DOWN_3)
        self.LowA_6.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowA_6.setStyleSheet("background-color: green")
        self.LowA_6.setObjectName("LowA_6")
        self.Buffer_UP_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_UP_3.setGeometry(QtCore.QRect(97, 36, 120, 80))
        self.Buffer_UP_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_UP_3.setObjectName("Buffer_UP_3")
        self.HighA_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighA_7.setGeometry(QtCore.QRect(50, 50, 22, 22))
        self.HighA_7.setStyleSheet("background-color: green")
        self.HighA_7.setObjectName("HighA_7")
        self.HighB_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighB_7.setGeometry(QtCore.QRect(50, 26, 22, 22))
        self.HighB_7.setStyleSheet("background-color: green")
        self.HighB_7.setObjectName("HighB_7")
        self.HighC_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.HighC_7.setGeometry(QtCore.QRect(50, 2, 22, 22))
        self.HighC_7.setStyleSheet("background-color: green")
        self.HighC_7.setObjectName("HighC_7")
        self.LowA_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowA_7.setGeometry(QtCore.QRect(25, 50, 22, 22))
        self.LowA_7.setStyleSheet("background-color: green")
        self.LowA_7.setObjectName("LowA_7")
        self.LowB_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowB_7.setGeometry(QtCore.QRect(25, 26, 22, 22))
        self.LowB_7.setStyleSheet("background-color: green")
        self.LowB_7.setObjectName("LowB_7")
        self.LowC_7 = QtWidgets.QWidget(self.Buffer_UP_3)
        self.LowC_7.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.LowC_7.setStyleSheet("background-color: green")
        self.LowC_7.setObjectName("LowC_7")
        self.label_3 = QtWidgets.QLabel(self.Rout7)
        self.label_3.setGeometry(QtCore.QRect(20, -6, 291, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/Producer_Router.png"))
        self.label_3.setObjectName("label_3")
        self.Buffer_RIGHT_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_RIGHT_3.setGeometry(QtCore.QRect(170, 133, 120, 80))
        self.Buffer_RIGHT_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_RIGHT_3.setObjectName("Buffer_RIGHT_3")
        self.HighC_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighC_8.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighC_8.setStyleSheet("background-color: green")
        self.HighC_8.setObjectName("HighC_8")
        self.LowB_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowB_8.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_8.setStyleSheet("background-color: green")
        self.LowB_8.setObjectName("LowB_8")
        self.HighB_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighB_8.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_8.setStyleSheet("background-color: green")
        self.HighB_8.setObjectName("HighB_8")
        self.LowC_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowC_8.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowC_8.setStyleSheet("background-color: green")
        self.LowC_8.setObjectName("LowC_8")
        self.LowA_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.LowA_8.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowA_8.setStyleSheet("background-color: green")
        self.LowA_8.setObjectName("LowA_8")
        self.HighA_8 = QtWidgets.QWidget(self.Buffer_RIGHT_3)
        self.HighA_8.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighA_8.setStyleSheet("background-color: green")
        self.HighA_8.setObjectName("HighA_8")
        self.Buffer_LEFT_3 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_LEFT_3.setGeometry(QtCore.QRect(1, 133, 120, 80))
        self.Buffer_LEFT_3.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_LEFT_3.setObjectName("Buffer_LEFT_3")
        self.HighA_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighA_9.setGeometry(QtCore.QRect(73, 2, 22, 22))
        self.HighA_9.setStyleSheet("background-color: green")
        self.HighA_9.setObjectName("HighA_9")
        self.LowB_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowB_9.setGeometry(QtCore.QRect(49, 27, 22, 22))
        self.LowB_9.setStyleSheet("background-color: green")
        self.LowB_9.setObjectName("LowB_9")
        self.HighB_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighB_9.setGeometry(QtCore.QRect(49, 2, 22, 22))
        self.HighB_9.setStyleSheet("background-color: green")
        self.HighB_9.setObjectName("HighB_9")
        self.LowA_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowA_9.setGeometry(QtCore.QRect(73, 27, 22, 22))
        self.LowA_9.setStyleSheet("background-color: green")
        self.LowA_9.setObjectName("LowA_9")
        self.LowC_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.LowC_9.setGeometry(QtCore.QRect(25, 27, 22, 22))
        self.LowC_9.setStyleSheet("background-color: green")
        self.LowC_9.setObjectName("LowC_9")
        self.HighC_9 = QtWidgets.QWidget(self.Buffer_LEFT_3)
        self.HighC_9.setGeometry(QtCore.QRect(25, 2, 22, 22))
        self.HighC_9.setStyleSheet("background-color: green")
        self.HighC_9.setObjectName("HighC_9")
        self.Buffer_Slave_2 = QtWidgets.QWidget(self.Rout7)
        self.Buffer_Slave_2.setGeometry(QtCore.QRect(158, 194, 120, 80))
        self.Buffer_Slave_2.setStyleSheet("background-color: rgba(0,0,0,0)")
        self.Buffer_Slave_2.setObjectName("Buffer_Slave_2")
        self.HighC_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighC_10.setGeometry(QtCore.QRect(73, 2, 18, 18))
        self.HighC_10.setStyleSheet("background-color: green")
        self.HighC_10.setObjectName("HighC_10")
        self.LowB_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowB_10.setGeometry(QtCore.QRect(54, 23, 17, 18))
        self.LowB_10.setStyleSheet("background-color: green")
        self.LowB_10.setObjectName("LowB_10")
        self.HighB_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighB_10.setGeometry(QtCore.QRect(54, 2, 17, 18))
        self.HighB_10.setStyleSheet("background-color: green")
        self.HighB_10.setObjectName("HighB_10")
        self.LowC_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowC_10.setGeometry(QtCore.QRect(73, 23, 18, 18))
        self.LowC_10.setStyleSheet("background-color: green")
        self.LowC_10.setObjectName("LowC_10")
        self.LowA_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.LowA_10.setGeometry(QtCore.QRect(34, 23, 18, 18))
        self.LowA_10.setStyleSheet("background-color: green")
        self.LowA_10.setObjectName("LowA_10")
        self.HighA_10 = QtWidgets.QWidget(self.Buffer_Slave_2)
        self.HighA_10.setGeometry(QtCore.QRect(34, 2, 18, 18))
        self.HighA_10.setStyleSheet("background-color: green")
        self.HighA_10.setObjectName("HighA_10")
        self.label_3.raise_()
        self.Buffer_RIGHT_3.raise_()
        self.Buffer_LEFT_3.raise_()
        self.Buffer_Slave_2.raise_()
        self.Buffer_DOWN_3.raise_()
        self.Buffer_UP_3.raise_()
        self.Rout8.raise_()
        self.Router8_2.raise_()
        self.Router8_4.raise_()
        self.Router8_5.raise_()
        self.Router8_6.raise_()
        self.Router8_7.raise_()
        self.Router8_8.raise_()
        self.Router8_9.raise_()
        self.widget_9.raise_()
        self.widget_10.raise_()
        self.widget_11.raise_()
        self.widget_12.raise_()
        self.widget_34.raise_()
        self.widget_48.raise_()
        self.widget_49.raise_()
        self.widget_50.raise_()
        self.widget_51.raise_()
        self.Rout7.raise_()
        self.widget_47.raise_()
        self.widget_8.raise_()
        self.widget_33.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionToggle_Fullscreen = QtWidgets.QAction(MainWindow)
        self.actionToggle_Fullscreen.setObjectName("actionToggle_Fullscreen")
        self.menuSettings.addAction(self.actionToggle_Fullscreen)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.centralwidget.setFocusPolicy(Qt.StrongFocus)
    
    def UpdateGUI(self,data):
        #Routers
        routers = data['routers']
        #Get the list of Routers
        #print(routers)
        for name in ["Rout8"]:#routers.keys():
            router = self.centralwidget.findChild(QWidget, f"{name}")
            for child in router.children():
                if(child.objectName()[:11] == "Buffer_DOWN"):
                    colors = copy(routers[name]['port_2'])
                    while(len(colors) < 3):
                        colors.append("white")
                    for x in routers[name]['port_3']:
                        colors.append(x)
                    while(len(colors) < 6):
                        colors.append("white")
                    counter = 0
                    print(colors)
                    print(routers[name])
                    for buffer_point in child.children():
                        #print(buffer_point.objectName())
                        color = colors[counter]
                        if(color == "FREE"): color = "pink"
                        if(color[0] in ["C","D","U","L","R"]): color = "purple"
                        print(color,end="/")
                        buffer_point.setStyleSheet(f"background-color:{color}")
                        counter+= 1
                elif(child.objectName()[:11] == "Buffer_LEFT"):
                    colors = copy(routers[name]['port_4'])
                    while(len(colors) < 3):
                        colors.append("white")
                    for x in routers[name]['port_5']:
                        colors.append(x)
                    while(len(colors) < 6):
                        colors.append("white")
                    counter = 0
                    #print(routers[name])
                    for buffer_point in child.children():
                        color = colors[counter]
                        if(color == "FREE"): color = "pink"
                        if(color[0] in ["C","D","U","L","R"]): color = "purple"
                        buffer_point.setStyleSheet(f"background-color:{color}")
                        counter+= 1
                elif(child.objectName()[:12] == "Buffer_RIGHT"):
                    colors = copy(routers[name]['port_8'])
                    while(len(colors) < 3):
                        colors.append("white")
                    for x in routers[name]['port_9']:
                        colors.append(x)
                    while(len(colors) < 6):
                        colors.append("white")
                    counter = 0
                    #print(routers[name])
                    for buffer_point in child.children():
                        color = colors[counter]
                        if(color == "FREE"): color = "pink"
                        if(color[0] in ["C","D","U","L","R"]): color = "purple"
                        buffer_point.setStyleSheet(f"background-color:{color}")
                        counter+= 1
                elif(child.objectName()[:9] == "Buffer_UP"):
                    colors = copy(routers[name]['port_6'])
                    while(len(colors) < 3):
                        colors.append("white")
                    for x in routers[name]['port_7']:
                        colors.append(x)
                    while(len(colors) < 6):
                        colors.append("white")
                    counter = 0 
                    #print(routers[name])
                    for buffer_point in child.children():
                        color = colors[counter]
                        if(color == "FREE"): color = "pink"
                        if(color[0] in ["C","D","U","L","R"]): color = "purple"
                        buffer_point.setStyleSheet(f"background-color:{color}")
                        counter+= 1
                elif(child.objectName()[:12] == "Buffer_Slave"):
                    colors = copy(routers[name]['port_0'])
                    while(len(colors) < 3):
                        colors.append("white")
                    for x in routers[name]['port_1']:
                        colors.append(x)
                    while(len(colors) < 6):
                        colors.append("white")
                    counter = 0 
                    #print(routers[name])
                    for buffer_point in child.children():
                        color = colors[counter]
                        if(color == "FREE"): color = "pink"
                        if(color[0] in ["C","D","U","L","R"]): color = "purple"
                        buffer_point.setStyleSheet(f"background-color:{color}")
                        counter+= 1

        ##self.centralwidget.findChild(QWidget, f"{}")
        #for child in self.Router8.children():
        #    if(child.objectName() == "Buffer_DOWN"):
        #        for buffer_point in child.children():
        #            buffer_point.setStyleSheet("background-color:purple")
        #if(not data):
        #    self.LEFTHigh0.setStyleSheet(f"background-color:green")
        #for x in data:
        #    color = x
        #    if(color == "FREE"): color = "pink"
        #    if(color[0] in ["C","D","U","L","R"]): color = "purple"
        #    self.LEFTHigh0.setStyleSheet(f"background-color:{color}")
    def on_key_event(self, key):
        if(key.event_type == keyboard.KEY_DOWN):
            if(key.name == "space"):
                print("Space pressed")
                self.UpdateGUI(getJSONGUI())
            if(key.name == "e"):
                self.widget_10.setStyleSheet(f"background-color: blue")
            if(key.name == "q"):
                self.widget_10.setStyleSheet(f"background-color: purple")
            if(key.name == "esc"):
                self.Window.close()

def main():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Window(MainWindow)
    keyboard.hook(ui.on_key_event)
    MainWindow.show()
    MainWindow.setWindowState(Qt.WindowFullScreen)
    sys.exit(app.exec_())
main()
